#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
studio.taxonomy — 拼图游戏统一分类标签规范 (Single Source of Truth)
Generated by scripts/build_taxonomy.py. DO NOT EDIT DIRECTLY.
Source: data/taxonomy.json (v3.0.0, 2026-09-04)
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# 1. 核心主 Tags (14 个核心分类)
# ---------------------------------------------------------------------------

MAIN_TAGS: list[dict[str, Any]] = [
    {"id": "Landscapes", "name": "Landscapes", "zh": "风光", "icon": "🏔️", "desc": "宏观地理、壮阔山川、浩瀚天象", "grid_row": 1, "order": 1},
    {"id": "Nature", "name": "Nature", "zh": "自然", "icon": "🌲", "desc": "植物生态、奇趣真菌、四季物候", "grid_row": 1, "order": 2},
    {"id": "Flowers", "name": "Flowers", "zh": "花卉", "icon": "🌸", "desc": "浪漫名花、花海花艺、优雅园艺", "grid_row": 2, "order": 3},
    {"id": "Animals", "name": "Animals", "zh": "动物", "icon": "🦁", "desc": "野生生灵、飞禽鸟类、海洋水族", "grid_row": 2, "order": 4},
    {"id": "Pets", "name": "Pets", "zh": "宠物", "icon": "🐾", "desc": "家庭伴侣萌宠、治愈生灵", "grid_row": 2, "order": 5},
    {"id": "Travel", "name": "Travel", "zh": "旅行", "icon": "✈️", "desc": "城市天际线、名胜古迹、欧式古堡", "grid_row": 3, "order": 6},
    {"id": "Vehicles", "name": "Vehicles", "zh": "交通", "icon": "🚂", "desc": "交通载具、复古工业机械", "grid_row": 3, "order": 7},
    {"id": "Cozy", "name": "Cozy", "zh": "温馨", "icon": "☕", "desc": "治愈慢生活、室内温暖角、复古手作", "grid_row": 3, "order": 8},
    {"id": "Food", "name": "Food", "zh": "美食", "icon": "🍰", "desc": "烘焙甜点、环球料理、鲜果茶饮", "grid_row": 4, "order": 9},
    {"id": "Art", "name": "Art", "zh": "艺术", "icon": "🎨", "desc": "传世名画、唯美插画、二次元、国风", "grid_row": 4, "order": 10},
    {"id": "Fantasy", "name": "Fantasy", "zh": "奇幻", "icon": "✨", "desc": "魔法神兽、深空星系、占星图腾", "grid_row": 4, "order": 11},
    {"id": "Colors", "name": "Colors", "zh": "缤纷", "icon": "🌈", "desc": "曼陀罗图腾、平铺静物、彩虹渐变", "grid_row": 5, "order": 12},
    {"id": "Holidays", "name": "Holidays", "zh": "节日", "icon": "🎉", "desc": "节庆假日、民俗庆典、仪式装扮", "grid_row": 5, "order": 13},
    {"id": "Others", "name": "Others", "zh": "其他", "icon": "📦", "desc": "体育运动、无法归类的特殊小众素材", "grid_row": 5, "order": 14},
]

MAIN_TAG_IDS: list[str] = [t["id"] for t in MAIN_TAGS]
TAG_ZH: dict[str, str] = {t["id"]: t["zh"] for t in MAIN_TAGS}

# 兼容性别名映射 (代码向下兼容)
CATALOG_DEFS = MAIN_TAGS
SPECIFIC_TAG_DEFS = MAIN_TAGS

# ---------------------------------------------------------------------------
# 2. 细分标签与路径智能识别正则词表 (tag_patterns)
# ---------------------------------------------------------------------------

TAG_PATTERNS: dict[str, list[str]] = {
    "Landscapes": [
        r"landscape", r"mountain", r"peak", r"canyon", r"valley",
        r"cliff", r"scree", r"forest", r"wood", r"bamboo",
        r"jungle", r"ocean", r"sea\b", r"beach", r"coast",
        r"reef", r"wave", r"iceberg", r"sunset", r"sunrise",
        r"dusk", r"dawn", r"twilight", r"horizon", r"waterfall",
        r"lake", r"river", r"creek", r"stream", r"fjord",
        r"desert", r"dune", r"aurora", r"sky", r"cloud",
        r"rainbow",
    ],
    "Nature": [
        r"nature", r"botanical", r"succulent", r"cactus", r"bonsai",
        r"fern", r"leaf", r"foliage", r"mushroom", r"fungi",
        r"toadstool", r"moss", r"lichen", r"season", r"spring\b",
        r"summer", r"autumn", r"fall\b", r"winter", r"frost",
        r"snow_scene",
    ],
    "Flowers": [
        r"flower", r"floral", r"rose\b", r"roses\b", r"peony",
        r"tulip", r"sunflower", r"hydrangea", r"wisteria", r"cherry_blossom",
        r"lotus", r"water_lily", r"bouquet", r"garden", r"meadow",
        r"greenhouse",
    ],
    "Animals": [
        r"animal", r"wildlife", r"fauna", r"mammal", r"lion",
        r"tiger", r"leopard", r"cheetah", r"jaguar", r"bear\b",
        r"polar_bear", r"deer", r"stag", r"elk", r"wolf",
        r"fox\b", r"foxes\b", r"elephant", r"giraffe", r"zebra",
        r"rhino", r"hippo", r"monkey", r"panda", r"sloth",
        r"otter", r"bird", r"parrot", r"macaw", r"toucan",
        r"owl", r"eagle", r"hawk", r"swan", r"flamingo",
        r"peacock", r"penguin", r"hummingbird", r"kingfisher", r"sealife",
        r"marine", r"ocean_creature", r"whale", r"dolphin", r"orca",
        r"shark", r"turtle", r"sea_turtle", r"jellyfish", r"seahorse",
        r"stingray", r"octopus", r"coral_fish", r"insect", r"butterfly",
        r"dragonfly", r"beetle", r"chameleon", r"tree_frog",
    ],
    "Pets": [
        r"pet\b", r"pets\b", r"cat\b", r"cats\b", r"kitten",
        r"kitty", r"feline", r"ragdoll", r"british_shorthair", r"dog\b",
        r"dogs\b", r"puppy", r"puppies", r"canine", r"corgi",
        r"shiba", r"golden_retriever", r"labrador", r"poodle", r"bulldog",
        r"husky", r"samoyed", r"rabbit", r"bunny", r"bunnies",
        r"hare\b", r"guinea_pig", r"hamster", r"chinchilla", r"hedgehog",
        r"capybara", r"ferret", r"goldfish", r"betta", r"aquarium",
        r"budgie", r"call_duck",
    ],
    "Travel": [
        r"travel", r"place", r"trip", r"tour", r"cit(y|ies)",
        r"urban", r"skyline", r"metropolis", r"street", r"alley",
        r"canal", r"night_view", r"landmark", r"monument", r"eiffel",
        r"taj_mahal", r"colosseum", r"pyramid", r"big_ben", r"castle",
        r"palace", r"chateau", r"fortress", r"manor", r"village",
        r"town", r"old_town", r"water_town", r"cotswolds", r"santorini",
        r"architecture", r"building", r"bridge", r"cathedral", r"church",
        r"temple", r"shrine", r"pagoda", r"windmill", r"lighthouse",
    ],
    "Vehicles": [
        r"vehicle", r"transport", r"car\b", r"cars\b", r"automobile",
        r"classic_car", r"vintage_car", r"sports_car", r"camper", r"van\b",
        r"motorcycle", r"scooter", r"truck", r"train", r"locomotive",
        r"steam_train", r"railway", r"railroad", r"tram", r"metro",
        r"ship\b", r"ships\b", r"boat", r"sailboat", r"tall_ship",
        r"yacht", r"cruise", r"gondola", r"canoe", r"vessel",
        r"aircraft", r"airplane", r"plane\b", r"planes\b", r"biplane",
        r"balloon", r"hot_air_balloon", r"helicopter", r"airship",
    ],
    "Cozy": [
        r"cozy", r"coziness", r"cozyhome", r"snug", r"hygge",
        r"interior", r"room", r"living_room", r"bedroom", r"study",
        r"reading_nook", r"windowsill", r"balcony", r"kitchen", r"fireplace",
        r"hearth", r"bookshelf", r"cottage", r"cabin", r"log_cabin",
        r"chalet", r"thatched", r"lifestyle", r"reading", r"picnic",
        r"slow_living", r"tea_time", r"people", r"craft", r"handicraft",
        r"knitting", r"yarn", r"wool", r"sewing", r"embroidery",
        r"patchwork", r"pottery", r"woodworking", r"vintage", r"retro",
        r"nostalgia", r"americana", r"antique", r"typewriter", r"gramophone",
    ],
    "Food": [
        r"food", r"meal", r"dish", r"gourmet", r"dessert",
        r"sweet", r"cake", r"pastry", r"bakery", r"croissant",
        r"bread", r"macaron", r"donut", r"waffle", r"pancake",
        r"cookie", r"pie\b", r"ice_cream", r"chocolate", r"cuisine",
        r"sushi", r"ramen", r"pizza", r"pasta", r"steak",
        r"dim_sum", r"taco", r"burger", r"bbq", r"fruit",
        r"berry", r"berries", r"strawberry", r"citrus", r"lemon",
        r"apple", r"vegetable", r"harvest", r"drink", r"beverage",
        r"coffee", r"coffeetea", r"latte", r"tea\b", r"afternoon_tea",
        r"cocktail", r"wine", r"matcha",
    ],
    "Art": [
        r"art\b", r"arts\b", r"fine_?art", r"masterpiece", r"museum",
        r"painting", r"oil_painting", r"watercolor", r"acrylic", r"canvas",
        r"impressionism", r"van_gogh", r"monet", r"illustration", r"storybook",
        r"picture_book", r"whimsical", r"hand_drawn", r"sketch", r"anime",
        r"manga", r"cartoon", r"chibi", r"ghibli", r"cel_shaded",
        r"oriental", r"asian_art", r"chinese_painting", r"gongbi", r"ink_wash",
        r"blue_green_landscape", r"ukiyo_e",
    ],
    "Fantasy": [
        r"fantasy", r"fairy_tale", r"enchanted", r"mythical", r"mythology",
        r"dragon", r"unicorn", r"griffin", r"phoenix", r"kitsune",
        r"pegasus", r"mermaid", r"fairy", r"pixie", r"elf",
        r"elves", r"magic", r"wizard", r"witch", r"spell",
        r"potion", r"cauldron", r"crystal_cave", r"floating_island", r"portal",
        r"space", r"universe", r"cosmos", r"galaxy", r"galaxies",
        r"nebula", r"planet", r"saturn", r"earth", r"moon",
        r"astronaut", r"spaceship", r"space_station", r"sci_fi", r"zodiac",
        r"astrology", r"horoscope", r"constellation", r"tarot",
    ],
    "Colors": [
        r"color", r"colorful", r"rainbow", r"gradient", r"vibrant_palette",
        r"mandala", r"kaleidoscope", r"fractal", r"symmetry", r"stained_glass",
        r"mosaic", r"flat_?lay", r"knolling", r"collage", r"assortment",
        r"overhead_table", r"abstract", r"fluid_art", r"acrylic_pour", r"marble_texture",
        r"pattern", r"geometry",
    ],
    "Holidays": [
        r"holiday", r"festival", r"celebration", r"christmas", r"xmas",
        r"santa", r"reindeer", r"gingerbread", r"halloween", r"jack_o_lantern",
        r"pumpkin", r"easter", r"easter_egg", r"new_?year", r"spring_festival",
        r"chinese_new_year", r"lunar_new_year", r"lantern", r"thanksgiving", r"turkey",
        r"valentine",
    ],
    "Others": [
        r"\bsports?\b", r"athletics?", r"stadium", r"skiing", r"surfing",
        r"soccer", r"football", r"\bothers?\b", r"\bmisc\b",
    ],
}

# 中文别名快速映射字典
ZH_ALIAS_MAP: dict[str, str] = {
    "风光": "Landscapes", "风景": "Landscapes", "雪山": "Landscapes", "山峦": "Landscapes", "湖泊": "Landscapes",
    "森林": "Landscapes", "海洋": "Landscapes", "海滩": "Landscapes", "日落": "Landscapes", "晚霞": "Landscapes",
    "自然": "Nature", "植物": "Nature", "多肉": "Nature", "绿植": "Nature", "蘑菇": "Nature",
    "真菌": "Nature", "四季": "Nature", "花卉": "Flowers", "花朵": "Flowers", "花园": "Flowers",
    "花海": "Flowers", "插花": "Flowers", "玫瑰": "Flowers", "牡丹": "Flowers", "郁金香": "Flowers",
    "动物": "Animals", "野生动物": "Animals", "野兽": "Animals", "鸟类": "Animals", "飞禽": "Animals",
    "海洋水族": "Animals", "水族": "Animals", "宠物": "Pets", "萌宠": "Pets", "猫咪": "Pets",
    "猫": "Pets", "狗狗": "Pets", "狗": "Pets", "兔子": "Pets", "仓鼠": "Pets",
    "荷兰猪": "Pets", "旅行": "Travel", "城市": "Travel", "建筑": "Travel", "地标": "Travel",
    "古堡": "Travel", "城堡": "Travel", "小镇": "Travel", "古镇": "Travel", "街景": "Travel",
    "交通": "Vehicles", "机械": "Vehicles", "汽车": "Vehicles", "跑车": "Vehicles", "火车": "Vehicles",
    "列车": "Vehicles", "船舶": "Vehicles", "帆船": "Vehicles", "飞机": "Vehicles", "温馨": "Cozy",
    "生活": "Cozy", "室内": "Cozy", "木屋": "Cozy", "手作": "Cozy", "复古": "Cozy",
    "日常": "Cozy", "美食": "Food", "料理": "Food", "甜品": "Food", "甜点": "Food",
    "烘焙": "Food", "蛋糕": "Food", "水果": "Food", "咖啡": "Food", "茶饮": "Food",
    "艺术": "Art", "名画": "Art", "油画": "Art", "插画": "Art", "绘本": "Art",
    "动漫": "Art", "二次元": "Art", "国风": "Art", "水墨": "Art", "奇幻": "Fantasy",
    "科幻": "Fantasy", "神兽": "Fantasy", "巨龙": "Fantasy", "魔法": "Fantasy", "太空": "Fantasy",
    "星云": "Fantasy", "星座": "Fantasy", "缤纷": "Colors", "色彩": "Colors", "曼陀罗": "Colors",
    "平铺": "Colors", "色块": "Colors", "抽象": "Colors", "节日": "Holidays", "节庆": "Holidays",
    "圣诞": "Holidays", "万圣": "Holidays", "复活节": "Holidays", "春节": "Holidays", "新年": "Holidays",
    "其他": "Others", "运动": "Others", "体育": "Others",
}
_ZH_ALIAS_MAP = ZH_ALIAS_MAP

# 历史前缀兼容 (cat_*)
LEGACY_CAT_MAP: dict[str, str] = {
    "cat_nature": "Nature",
    "cat_animals": "Animals",
    "cat_pets": "Pets",
    "cat_colors": "Colors",
    "cat_flowers": "Flowers",
    "cat_cozy": "Cozy",
    "cat_travel": "Travel",
    "cat_vehicles": "Vehicles",
    "cat_food": "Food",
    "cat_art": "Art",
    "cat_fantasy": "Fantasy",
    "cat_holidays": "Holidays",
    "cat_landscapes": "Landscapes",
    "cat_others": "Others",
}
_LEGACY_CAT_MAP = LEGACY_CAT_MAP

# 预编译正则，提升百万次扫描推断性能
COMPILED_PATTERNS: dict[str, list[re.Pattern]] = {
    tag: [re.compile(p, re.IGNORECASE) for p in patterns]
    for tag, patterns in TAG_PATTERNS.items()
}
_COMPILED_PATTERNS = COMPILED_PATTERNS

# ---------------------------------------------------------------------------
# 3. 归一化与路径智能推断 API
# ---------------------------------------------------------------------------

def get_main_tags() -> list[dict[str, Any]]:
    """获取 14 个核心主 Tags 清单（含 ID、中文名、描述、图标）。"""
    return MAIN_TAGS


def normalize_tag(tag: str | None) -> str:
    """
    将任意输入的字符串标签归一化为标准的 14 主 Tag ID 之一。
    例如:
      'cats' -> 'Pets'
      'cat_animals' -> 'Animals'
      'mountains' -> 'Landscapes'
      'coffee' -> 'Food'
      '猫咪' -> 'Pets'
      'Unknown' -> 'Others'
    """
    if not tag:
        return "Others"

    cleaned = str(tag).strip()
    if not cleaned:
        return "Others"

    # 1. 检查中文别名映射
    if cleaned in _ZH_ALIAS_MAP:
        return _ZH_ALIAS_MAP[cleaned]

    # 2. 检查是否带历史 cat_ 前缀
    lower_cleaned = cleaned.lower()
    if lower_cleaned in _LEGACY_CAT_MAP:
        return _LEGACY_CAT_MAP[lower_cleaned]

    # 3. 检查直接匹配主 Tag (大小写不敏感)
    for main_tag in MAIN_TAG_IDS:
        if lower_cleaned == main_tag.lower():
            return main_tag

    # 4. 检查是否能通过 patterns 识别
    for main_tag, patterns in _COMPILED_PATTERNS.items():
        for pat in patterns:
            if pat.search(cleaned):
                return main_tag

    return "Others"


def normalize_tags(tags: list[str] | None) -> list[str]:
    """
    将标签列表逐一归一化，去重并保持原始顺序。若全部无法匹配则返回 ['Others']。
    """
    if not tags:
        return ["Others"]

    result: list[str] = []
    seen: set[str] = set()

    for t in tags:
        norm = normalize_tag(t)
        if norm not in seen:
            seen.add(norm)
            result.append(norm)

    return result if result else ["Others"]


def infer_tags_from_path(path: str | Path, root: Path | None = None) -> list[str]:
    """
    从图片文件的路径语义（优先最内层父目录名）智能推断应赋予的主 Tags。
    规则：严格从各级父目录名识别，绝不从文件名推断（避免文件名随机命名导致误判）。
    """
    p = Path(path)

    # 如果有 root 且属于 root 下的子路径，取相对路径解析
    if root is not None:
        try:
            p = p.relative_to(root)
        except Exception:
            pass

    # 目录层级（从最靠近文件的父目录向上遍历）
    parent_dirs = list(p.parts[:-1]) if len(p.parts) > 1 else []

    # 1. 优先从最靠近文件的父目录开始识别
    for d in reversed(parent_dirs):
        norm = normalize_tag(d)
        if norm != "Others":
            return [norm]

    # 2. 回退检查祖先目录名正则（不检查文件名，避免文件名随机字符串造成误判）
    for d in reversed(parent_dirs):
        for main_tag, patterns in _COMPILED_PATTERNS.items():
            if main_tag == "Others":
                continue
            for pat in patterns:
                if pat.search(d):
                    return [main_tag]

    return ["Others"]


def suggest_tags_for_image(filename: str, parent_dirs: list[str] | None = None) -> list[str]:
    """基于文件名和父目录列表推荐标签。若有父目录优先从目录识别，无目录时才从文件名识别。"""
    if parent_dirs:
        for d in reversed(parent_dirs):
            norm = normalize_tag(d)
            if norm != "Others":
                return [norm]
    stem = Path(filename).stem
    norm = normalize_tag(stem)
    return [norm]


# ---------------------------------------------------------------------------
# 4. 兼容性导出 (向下兼容历史调用方)
# ---------------------------------------------------------------------------
ALL_CANONICAL_TAGS: list[str] = MAIN_TAG_IDS
CATALOG_TO_TAGS_MAP: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}
TAG_TO_CATALOGS: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}
normalize_token = normalize_tag
guess_tags_from_path = infer_tags_from_path
get_catalogs_for_tags = normalize_tags
