#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
studio.taxonomy — 拼图游戏统一分类标签规范 (Single Source of Truth)
Generated by scripts/build_taxonomy.py. DO NOT EDIT DIRECTLY.
Source: data/taxonomy.json (v3.2.0, 2026-09-07)
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any
import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# 1. 核心主 Tags (17 个核心分类)
# ---------------------------------------------------------------------------

MAIN_TAGS: list[dict[str, Any]] = [
    {"id": "Landscapes", "name": "Landscapes", "zh": "风光", "icon": "🏔️", "desc": "宏观地理、壮阔山川、浩瀚天象", "grid_row": 1, "order": 1},
    {"id": "Nature", "name": "Nature", "zh": "自然", "icon": "🌲", "desc": "植物生态、奇趣真菌、四季物候", "grid_row": 1, "order": 2},
    {"id": "Flowers", "name": "Flowers", "zh": "花卉", "icon": "🌸", "desc": "浪漫名花、花海花艺、优雅园艺", "grid_row": 2, "order": 3},
    {"id": "Animals", "name": "Animals", "zh": "动物", "icon": "🦁", "desc": "野生生灵、飞禽鸟类、海洋水族", "grid_row": 2, "order": 4},
    {"id": "Pets", "name": "Pets", "zh": "宠物", "icon": "🐾", "desc": "家庭伴侣萌宠、治愈生灵", "grid_row": 2, "order": 5},
    {"id": "Cities", "name": "Cities", "zh": "城市", "icon": "🏙️", "desc": "城市天际线、都市夜景、市井街巷、水乡运河", "grid_row": 3, "order": 6},
    {"id": "Structures", "name": "Structures", "zh": "建筑", "icon": "🏛️", "desc": "知名地标建筑、古堡宫殿、桥梁灯塔、几何构造", "grid_row": 3, "order": 7},
    {"id": "Vehicles", "name": "Vehicles", "zh": "交通", "icon": "🚂", "desc": "交通载具、工业机械、出行工具", "grid_row": 3, "order": 8},
    {"id": "People", "name": "People", "zh": "人物", "icon": "👥", "desc": "人物肖像、时尚写真、童话角色、日常生活人物", "grid_row": 4, "order": 9},
    {"id": "Objects", "name": "Objects", "zh": "物品", "icon": "📦", "desc": "复古器物、静物台饰、日常用品、手工工艺品", "grid_row": 4, "order": 10},
    {"id": "Food", "name": "Food", "zh": "美食", "icon": "🍰", "desc": "烘焙甜点、环球料理、鲜果茶饮", "grid_row": 4, "order": 11},
    {"id": "Art", "name": "Art", "zh": "艺术", "icon": "🎨", "desc": "艺术插画、手绘绘本、AI生成插画、传世名画", "grid_row": 5, "order": 12},
    {"id": "Fantasy", "name": "Fantasy", "zh": "奇幻", "icon": "✨", "desc": "魔法神兽、深空星系、占星图腾、神秘异界", "grid_row": 5, "order": 13},
    {"id": "Holidays", "name": "Holidays", "zh": "庆典", "icon": "🎉", "desc": "节庆假日、盛大庆典、民俗活动、体育运动赛事", "grid_row": 5, "order": 14},
    {"id": "Colors", "name": "Colors", "zh": "色彩", "icon": "🌈", "desc": "【附加Tag】彩虹色谱渐变、纯色冲击、强烈撞色、流体色相（运营手动指定）", "grid_row": 6, "order": 15},
    {"id": "Composition", "name": "Composition", "zh": "组合", "icon": "🧩", "desc": "【附加Tag】平铺俯拍、模块化排布、拼贴组合、万花筒对称（运营手动指定）", "grid_row": 6, "order": 16},
    {"id": "Others", "name": "Others", "zh": "其他", "icon": "💡", "desc": "无法明确归类的特殊杂项素材兜底", "grid_row": 6, "order": 17},
]

MAIN_TAG_IDS: list[str] = [t["id"] for t in MAIN_TAGS]
TAG_ZH: dict[str, str] = {t["id"]: t["zh"] for t in MAIN_TAGS}

# 兜底标签的**唯一规范形式**（全链路只认这一个大小写）。
# 约定：素材没有标签 / 标签无法归类时，tags 一律写成 [OTHERS_TAG]，
# 而不是空数组 [] 或小写 "others"。这样"是否未分类"在任何地方都等价于
# `OTHERS_TAG in tags`，排序/筛选/统计规则得以完全统一。
OTHERS_TAG = "Others"

# 兼容性别名映射 (代码向下兼容)
CATALOG_DEFS = MAIN_TAGS
SPECIFIC_TAG_DEFS = MAIN_TAGS

# ---------------------------------------------------------------------------
# 2. 细分标签与路径智能识别正则词表 (tag_patterns)
# ---------------------------------------------------------------------------

TAG_PATTERNS: dict[str, list[str]] = {
    "Landscapes": [
        r"landscape", r"mountain", r"(?<![a-z])peaks?(?![a-z])", r"(?<![a-z])summits?(?![a-z])", r"(?<![a-z])canyons?(?![a-z])",
        r"(?<![a-z])valleys?(?![a-z])", r"(?<![a-z])cliffs?(?![a-z])", r"plateau", r"(?<![a-z])mesas?(?![a-z])", r"(?<![a-z])gorges?(?![a-z])",
        r"(?<![a-z])ravines?(?![a-z])", r"(?<![a-z])fjords?(?![a-z])", r"(?<![a-z])craters?(?![a-z])", r"volcano", r"(?<![a-z])geysers?(?![a-z])",
        r"glacier", r"(?<![a-z])tundras?(?![a-z])", r"(?<![a-z])deserts?(?![a-z])", r"(?<![a-z])dunes?(?![a-z])", r"(?<![a-z])oasis(?![a-z])",
        r"prairie", r"(?<![a-z])steppes?(?![a-z])", r"savanna", r"(?<![a-z])swamps?(?![a-z])", r"(?<![a-z])marshs?(?![a-z])",
        r"wetland", r"(?<![a-z])moors?(?![a-z])", r"countryside", r"farmland", r"highland",
        r"lowland", r"(?<![a-z])oceans?(?![a-z])", r"(?<![a-z])seas?(?![a-z])", r"(?<![a-z])beachs?(?![a-z])", r"(?<![a-z])coasts?(?![a-z])",
        r"coastline", r"(?<![a-z])shores?(?![a-z])", r"seascape", r"seaside", r"(?<![a-z])reefs?(?![a-z])",
        r"(?<![a-z])waves?(?![a-z])", r"waterfall", r"(?<![a-z])lakes?(?![a-z])", r"(?<![a-z])rivers?(?![a-z])", r"(?<![a-z])creeks?(?![a-z])",
        r"(?<![a-z])streams?(?![a-z])", r"(?<![a-z])rapids(?![a-z])", r"(?<![a-z])bays?(?![a-z])", r"(?<![a-z])lagoons?(?![a-z])", r"(?<![a-z])atolls?(?![a-z])",
        r"(?<![a-z])islands?(?![a-z])", r"peninsula", r"iceberg", r"(?<![a-z])forests?(?![a-z])", r"(?<![a-z])woods?(?![a-z])",
        r"(?<![a-z])bamboos?(?![a-z])", r"(?<![a-z])jungles?(?![a-z])", r"(?<![a-z])fields?(?![a-z])", r"(?<![a-z])hills?(?![a-z])", r"(?<![a-z])skys?(?![a-z])",
        r"(?<![a-z])clouds?(?![a-z])", r"(?<![a-z])sunsets?(?![a-z])", r"sunrise", r"(?<![a-z])dusks?(?![a-z])", r"(?<![a-z])dawns?(?![a-z])",
        r"twilight", r"horizon", r"(?<![a-z])auroras?(?![a-z])", r"northern_lights", r"milky_way",
        r"star_trail", r"night_sky", r"starry_sky", r"(?<![a-z])moons?(?![a-z])", r"moonset",
        r"(?<![a-z])mists?(?![a-z])", r"(?<![a-z])fogs?(?![a-z])", r"(?<![a-z])storms?(?![a-z])", r"lightning", r"(?<![a-z])snows?(?![a-z])",
        r"golden_hour", r"blue_hour",
    ],
    "Nature": [
        r"(?<![a-z])natures?(?![a-z])", r"botanical", r"(?<![a-z])plants?(?![a-z])", r"(?<![a-z])herbs?(?![a-z])", r"(?<![a-z])vines?(?![a-z])",
        r"(?<![a-z])ivys?(?![a-z])", r"succulent", r"(?<![a-z])cactus(?![a-z])", r"(?<![a-z])bonsais?(?![a-z])", r"(?<![a-z])ferns?(?![a-z])",
        r"(?<![a-z])leafs?(?![a-z])", r"foliage", r"mashrooms", r"(?<![a-z])fungis?(?![a-z])", r"(?<![a-z])moss(?![a-z])",
        r"(?<![a-z])lichens?(?![a-z])", r"(?<![a-z])trees?(?![a-z])", r"(?<![a-z])branchs?(?![a-z])", r"(?<![a-z])barks?(?![a-z])", r"(?<![a-z])roots?(?![a-z])",
        r"(?<![a-z])trunks?(?![a-z])", r"(?<![a-z])pines?(?![a-z])", r"(?<![a-z])maples?(?![a-z])", r"(?<![a-z])oaks?(?![a-z])", r"(?<![a-z])birchs?(?![a-z])",
        r"(?<![a-z])palms?(?![a-z])", r"(?<![a-z])sprouts?(?![a-z])", r"(?<![a-z])seeds?(?![a-z])", r"pinecone", r"(?<![a-z])acorns?(?![a-z])",
        r"(?<![a-z])nests?(?![a-z])", r"(?<![a-z])hives?(?![a-z])", r"dewdrop", r"(?<![a-z])ripples?(?![a-z])", r"sunlight",
        r"forest_floor", r"undergrowth", r"(?<![a-z])seasons?(?![a-z])", r"(?<![a-z])summers?(?![a-z])", r"(?<![a-z])autumns?(?![a-z])",
        r"(?<![a-z])winters?(?![a-z])", r"(?<![a-z])frosts?(?![a-z])", r"(?<![a-z])stones?(?![a-z])", r"(?<![a-z])pebbles?(?![a-z])", r"(?<![a-z])soils?(?![a-z])",
        r"mineral", r"crystal", r"(?<![a-z])geodes?(?![a-z])", r"seashell", r"driftwood",
        r"wilderness", r"grassland",
    ],
    "Flowers": [
        r"(?<![a-z])flowers?(?![a-z])", r"(?<![a-z])florals?(?![a-z])", r"blossom", r"(?<![a-z])petals?(?![a-z])", r"bouquet",
        r"greenhouse", r"(?<![a-z])roses?(?![a-z])", r"(?<![a-z])peonys?(?![a-z])", r"(?<![a-z])tulips?(?![a-z])", r"sunflower",
        r"hydrangea", r"wisteria", r"cherry_blossom", r"(?<![a-z])sakuras?(?![a-z])", r"plum_blossom",
        r"peach_blossom", r"apple_blossom", r"(?<![a-z])lotus(?![a-z])", r"water_lily", r"(?<![a-z])daisys?(?![a-z])",
        r"(?<![a-z])lilys?(?![a-z])", r"(?<![a-z])orchids?(?![a-z])", r"(?<![a-z])iris(?![a-z])", r"lavender", r"marigold",
        r"daffodil", r"(?<![a-z])poppys?(?![a-z])", r"carnation", r"chrysanthemum", r"(?<![a-z])dahlias?(?![a-z])",
        r"gladiolus", r"(?<![a-z])azaleas?(?![a-z])", r"camellia", r"jasmine", r"(?<![a-z])lilacs?(?![a-z])",
        r"magnolia", r"wildflower", r"gerbera", r"freesia", r"hyacinth",
        r"(?<![a-z])proteas?(?![a-z])", r"anemone", r"(?<![a-z])gardens?(?![a-z])", r"rose_garden", r"botanical_garden",
        r"flower_field", r"lavender_field", r"sunflower_field", r"tulip_field", r"florist",
    ],
    "Animals": [
        r"(?<![a-z])animals?(?![a-z])", r"wildlife", r"(?<![a-z])faunas?(?![a-z])", r"(?<![a-z])mammals?(?![a-z])", r"(?<![a-z])safaris?(?![a-z])",
        r"(?<![a-z])zoos?(?![a-z])", r"(?<![a-z])aviarys?(?![a-z])", r"(?<![a-z])lions?(?![a-z])", r"(?<![a-z])tigers?(?![a-z])", r"leopard",
        r"cheetah", r"(?<![a-z])jaguars?(?![a-z])", r"panther", r"(?<![a-z])lynxs?(?![a-z])", r"(?<![a-z])bobcats?(?![a-z])",
        r"(?<![a-z])coyotes?(?![a-z])", r"(?<![a-z])wolfs?(?![a-z])", r"(?<![a-z])bears?(?![a-z])", r"polar_bear", r"(?<![a-z])pandas?(?![a-z])",
        r"red_panda", r"(?<![a-z])deers?(?![a-z])", r"(?<![a-z])stags?(?![a-z])", r"(?<![a-z])elks?(?![a-z])", r"(?<![a-z])mooses?(?![a-z])",
        r"caribou", r"antelope", r"gazelle", r"(?<![a-z])impalas?(?![a-z])", r"wildebeest",
        r"(?<![a-z])bisons?(?![a-z])", r"buffalo", r"(?<![a-z])yaks?(?![a-z])", r"(?<![a-z])camels?(?![a-z])", r"(?<![a-z])llamas?(?![a-z])",
        r"(?<![a-z])alpacas?(?![a-z])", r"giraffe", r"(?<![a-z])zebras?(?![a-z])", r"(?<![a-z])rhinos?(?![a-z])", r"(?<![a-z])hippos?(?![a-z])",
        r"elephant", r"(?<![a-z])sheeps?(?![a-z])", r"(?<![a-z])goats?(?![a-z])", r"(?<![a-z])cattles?(?![a-z])", r"(?<![a-z])foxs?(?![a-z])",
        r"raccoon", r"(?<![a-z])skunks?(?![a-z])", r"(?<![a-z])beavers?(?![a-z])", r"squirrel", r"chipmunk",
        r"hedgehog", r"porcupine", r"armadillo", r"anteater", r"(?<![a-z])sloths?(?![a-z])",
        r"(?<![a-z])otters?(?![a-z])", r"(?<![a-z])badgers?(?![a-z])", r"(?<![a-z])moles?(?![a-z])", r"meerkat", r"(?<![a-z])hyenas?(?![a-z])",
        r"capybara", r"kangaroo", r"(?<![a-z])koalas?(?![a-z])", r"(?<![a-z])monkeys?(?![a-z])", r"(?<![a-z])apes?(?![a-z])",
        r"gorilla", r"chimpanzee", r"orangutan", r"(?<![a-z])lemurs?(?![a-z])", r"(?<![a-z])gibbons?(?![a-z])",
        r"(?<![a-z])birds?(?![a-z])", r"(?<![a-z])parrots?(?![a-z])", r"(?<![a-z])macaws?(?![a-z])", r"(?<![a-z])toucans?(?![a-z])", r"(?<![a-z])owls?(?![a-z])",
        r"(?<![a-z])eagles?(?![a-z])", r"(?<![a-z])hawks?(?![a-z])", r"(?<![a-z])falcons?(?![a-z])", r"vulture", r"(?<![a-z])swans?(?![a-z])",
        r"flamingo", r"peacock", r"penguin", r"hummingbird", r"kingfisher",
        r"woodpecker", r"swallow", r"nightingale", r"(?<![a-z])ducks?(?![a-z])", r"(?<![a-z])gooses?(?![a-z])",
        r"(?<![a-z])cranes?(?![a-z])", r"(?<![a-z])herons?(?![a-z])", r"(?<![a-z])egrets?(?![a-z])", r"(?<![a-z])storks?(?![a-z])", r"pelican",
        r"(?<![a-z])puffins?(?![a-z])", r"seagull", r"(?<![a-z])gulls?(?![a-z])", r"sparrow", r"(?<![a-z])robins?(?![a-z])",
        r"(?<![a-z])finchs?(?![a-z])", r"(?<![a-z])canarys?(?![a-z])", r"cardinal", r"(?<![a-z])magpies?(?![a-z])", r"(?<![a-z])ravens?(?![a-z])",
        r"(?<![a-z])doves?(?![a-z])", r"(?<![a-z])pigeons?(?![a-z])", r"ostrich", r"sealife", r"(?<![a-z])marines?(?![a-z])",
        r"ocean_creature", r"(?<![a-z])whales?(?![a-z])", r"dolphin", r"(?<![a-z])orcas?(?![a-z])", r"(?<![a-z])sharks?(?![a-z])",
        r"(?<![a-z])turtles?(?![a-z])", r"sea_turtle", r"jellyfish", r"seahorse", r"stingray",
        r"octopus", r"coral_fish", r"starfish", r"sea_urchin", r"manta_ray",
        r"(?<![a-z])seals?(?![a-z])", r"sea_lion", r"(?<![a-z])walrus(?![a-z])", r"manatee", r"(?<![a-z])dugongs?(?![a-z])",
        r"sea_otter", r"(?<![a-z])insects?(?![a-z])", r"butterfly", r"dragonfly", r"(?<![a-z])beetles?(?![a-z])",
        r"ladybug", r"firefly", r"grasshopper", r"(?<![a-z])mantis(?![a-z])", r"caterpillar",
        r"chameleon", r"tree_frog", r"(?<![a-z])snakes?(?![a-z])", r"(?<![a-z])pythons?(?![a-z])", r"(?<![a-z])vipers?(?![a-z])",
        r"(?<![a-z])lizards?(?![a-z])", r"(?<![a-z])geckos?(?![a-z])", r"(?<![a-z])iguanas?(?![a-z])", r"tortoise", r"crocodile",
        r"alligator", r"(?<![a-z])frogs?(?![a-z])", r"(?<![a-z])toads?(?![a-z])", r"salamander", r"(?<![a-z])newts?(?![a-z])",
    ],
    "Pets": [
        r"(?<![a-z])pets?(?![a-z])", r"(?<![a-z])cats?(?![a-z])", r"(?<![a-z])kittens?(?![a-z])", r"(?<![a-z])kittys?(?![a-z])", r"(?<![a-z])felines?(?![a-z])",
        r"ragdoll", r"british_shorthair", r"persian", r"siamese", r"maine_coon",
        r"(?<![a-z])sphynxs?(?![a-z])", r"(?<![a-z])bengals?(?![a-z])", r"(?<![a-z])dogs?(?![a-z])", r"(?<![a-z])puppys?(?![a-z])", r"(?<![a-z])canines?(?![a-z])",
        r"(?<![a-z])corgis?(?![a-z])", r"(?<![a-z])shibas?(?![a-z])", r"golden_retriever", r"labrador", r"(?<![a-z])poodles?(?![a-z])",
        r"bulldog", r"(?<![a-z])huskys?(?![a-z])", r"samoyed", r"(?<![a-z])beagles?(?![a-z])", r"dachshund",
        r"(?<![a-z])pugs?(?![a-z])", r"german_shepherd", r"terrier", r"pomeranian", r"chihuahua",
        r"border_collie", r"(?<![a-z])akitas?(?![a-z])", r"maltese", r"(?<![a-z])rabbits?(?![a-z])", r"(?<![a-z])bunnys?(?![a-z])",
        r"(?<![a-z])hares?(?![a-z])", r"guinea_pig", r"hamster", r"chinchilla", r"(?<![a-z])gerbils?(?![a-z])",
        r"(?<![a-z])ferrets?(?![a-z])", r"goldfish", r"(?<![a-z])bettas?(?![a-z])", r"aquarium", r"(?<![a-z])kois?(?![a-z])",
        r"(?<![a-z])guppys?(?![a-z])", r"angelfish", r"parakeet", r"cockatiel", r"call_duck",
        r"(?<![a-z])spiders?(?![a-z])", r"tarantula", r"scorpion", r"hermit_crab",
    ],
    "Cities": [
        r"(?<![a-z])urbans?(?![a-z])", r"cityscape", r"skyline", r"metropolis", r"downtown",
        r"(?<![a-z])streets?(?![a-z])", r"(?<![a-z])alleys?(?![a-z])", r"(?<![a-z])canals?(?![a-z])", r"night_view", r"village",
        r"(?<![a-z])towns?(?![a-z])", r"old_town", r"water_town", r"(?<![a-z])plazas?(?![a-z])", r"(?<![a-z])avenues?(?![a-z])",
        r"boulevard", r"(?<![a-z])markets?(?![a-z])", r"(?<![a-z])bazaars?(?![a-z])", r"(?<![a-z])souks?(?![a-z])", r"(?<![a-z])suburbs?(?![a-z])",
        r"highway", r"waterfront", r"riverside", r"lakeside", r"(?<![a-z])harbors?(?![a-z])",
        r"neighborhood", r"crossroad", r"cotswolds", r"santorini", r"(?<![a-z])paris(?![a-z])",
        r"(?<![a-z])londons?(?![a-z])", r"(?<![a-z])tokyos?(?![a-z])", r"(?<![a-z])kyotos?(?![a-z])", r"(?<![a-z])osakas?(?![a-z])", r"(?<![a-z])seouls?(?![a-z])",
        r"beijing", r"shanghai", r"hong_kong", r"new_york", r"san_francisco",
        r"(?<![a-z])venices?(?![a-z])", r"(?<![a-z])romes?(?![a-z])", r"florence", r"barcelona", r"(?<![a-z])lisbons?(?![a-z])",
        r"(?<![a-z])viennas?(?![a-z])", r"(?<![a-z])pragues?(?![a-z])", r"budapest", r"amsterdam", r"istanbul",
        r"(?<![a-z])dubais?(?![a-z])", r"marrakech", r"^cit(y|ies)$",
    ],
    "Structures": [
        r"architecture", r"building", r"(?<![a-z])bridges?(?![a-z])", r"landmark", r"monument",
        r"(?<![a-z])eiffels?(?![a-z])", r"taj_mahal", r"colosseum", r"pyramid", r"(?<![a-z])big_bens?(?![a-z])",
        r"(?<![a-z])castles?(?![a-z])", r"(?<![a-z])palaces?(?![a-z])", r"chateau", r"fortress", r"(?<![a-z])manors?(?![a-z])",
        r"citadel", r"cathedral", r"basilica", r"(?<![a-z])churchs?(?![a-z])", r"(?<![a-z])chapels?(?![a-z])",
        r"(?<![a-z])temples?(?![a-z])", r"(?<![a-z])shrines?(?![a-z])", r"(?<![a-z])pagodas?(?![a-z])", r"(?<![a-z])mosques?(?![a-z])", r"synagogue",
        r"monastery", r"(?<![a-z])abbeys?(?![a-z])", r"(?<![a-z])toriis?(?![a-z])", r"(?<![a-z])stupas?(?![a-z])", r"minaret",
        r"windmill", r"lighthouse", r"observatory", r"aqueduct", r"viaduct",
        r"(?<![a-z])tunnels?(?![a-z])", r"skyscraper", r"high_rise", r"(?<![a-z])towers?(?![a-z])", r"clock_tower",
        r"bell_tower", r"(?<![a-z])domes?(?![a-z])", r"(?<![a-z])spires?(?![a-z])", r"(?<![a-z])facades?(?![a-z])", r"(?<![a-z])roofs?(?![a-z])",
        r"(?<![a-z])columns?(?![a-z])", r"colonnade", r"portico", r"(?<![a-z])arcades?(?![a-z])", r"obelisk",
        r"(?<![a-z])statues?(?![a-z])", r"sculpture", r"fountain", r"memorial", r"mausoleum",
        r"(?<![a-z])tombs?(?![a-z])", r"graveyard", r"cemetery", r"interior", r"living_room",
        r"bedroom", r"kitchen", r"bathroom", r"dining_room", r"(?<![a-z])studys?(?![a-z])",
        r"fireplace", r"(?<![a-z])hearths?(?![a-z])", r"(?<![a-z])attics?(?![a-z])", r"(?<![a-z])cellars?(?![a-z])", r"stairway",
        r"staircase", r"doorway", r"corridor", r"balcony", r"terrace",
        r"courtyard", r"(?<![a-z])patios?(?![a-z])", r"(?<![a-z])porchs?(?![a-z])", r"veranda", r"(?<![a-z])gazebos?(?![a-z])",
        r"pavilion", r"cottage", r"(?<![a-z])cabins?(?![a-z])", r"log_cabin", r"(?<![a-z])chalets?(?![a-z])",
        r"thatched", r"(?<![a-z])barns?(?![a-z])", r"farmhouse", r"(?<![a-z])villas?(?![a-z])", r"mansion",
        r"(?<![a-z])estates?(?![a-z])", r"apartment", r"(?<![a-z])condos?(?![a-z])", r"(?<![a-z])igloos?(?![a-z])", r"(?<![a-z])yurts?(?![a-z])",
        r"(?<![a-z])tents?(?![a-z])", r"(?<![a-z])huts?(?![a-z])", r"treehouse", r"boathouse", r"library",
        r"theater", r"(?<![a-z])cinemas?(?![a-z])", r"stadium", r"(?<![a-z])arenas?(?![a-z])", r"(?<![a-z])schools?(?![a-z])",
        r"hospital", r"(?<![a-z])hotels?(?![a-z])", r"restaurant", r"(?<![a-z])cafes?(?![a-z])", r"(?<![a-z])shops?(?![a-z])",
        r"(?<![a-z])stores?(?![a-z])", r"factory", r"warehouse", r"industrial", r"(?<![a-z])ruins?(?![a-z])",
        r"stone_circle", r"^structures?$",
    ],
    "Vehicles": [
        r"vehicle", r"transport", r"(?<![a-z])cars?(?![a-z])", r"automobile", r"classic_car",
        r"vintage_car", r"sports_car", r"muscle_car", r"convertible", r"roadster",
        r"electric_car", r"(?<![a-z])campers?(?![a-z])", r"motorhome", r"(?<![a-z])vans?(?![a-z])", r"(?<![a-z])trucks?(?![a-z])",
        r"pickup_truck", r"(?<![a-z])suvs?(?![a-z])", r"(?<![a-z])jeeps?(?![a-z])", r"motorcycle", r"scooter",
        r"bicycle", r"(?<![a-z])bikes?(?![a-z])", r"mountain_bike", r"road_bike", r"(?<![a-z])trains?(?![a-z])",
        r"locomotive", r"steam_train", r"railway", r"railroad", r"bullet_train",
        r"(?<![a-z])trams?(?![a-z])", r"(?<![a-z])metros?(?![a-z])", r"(?<![a-z])subways?(?![a-z])", r"monorail", r"cable_car",
        r"(?<![a-z])ships?(?![a-z])", r"(?<![a-z])boats?(?![a-z])", r"sailboat", r"tall_ship", r"(?<![a-z])yachts?(?![a-z])",
        r"(?<![a-z])cruises?(?![a-z])", r"gondola", r"(?<![a-z])canoes?(?![a-z])", r"(?<![a-z])kayaks?(?![a-z])", r"rowboat",
        r"(?<![a-z])ferrys?(?![a-z])", r"catamaran", r"speedboat", r"motorboat", r"fishing_boat",
        r"tugboat", r"houseboat", r"submarine", r"(?<![a-z])vessels?(?![a-z])", r"aircraft",
        r"airplane", r"(?<![a-z])planes?(?![a-z])", r"biplane", r"(?<![a-z])jets?(?![a-z])", r"fighter_jet",
        r"(?<![a-z])gliders?(?![a-z])", r"seaplane", r"balloon", r"hot_air_balloon", r"helicopter",
        r"airship", r"zeppelin", r"(?<![a-z])bus(?![a-z])", r"double_decker_bus", r"school_bus",
        r"(?<![a-z])taxis?(?![a-z])", r"police_car", r"fire_truck", r"ambulance", r"trolley",
        r"rickshaw", r"carriage", r"stagecoach", r"chariot", r"skateboard",
        r"electric_scooter", r"tractor", r"forklift", r"bulldozer", r"excavator",
        r"dump_truck",
    ],
    "People": [
        r"portrait", r"(?<![a-z])humans?(?![a-z])", r"(?<![a-z])girls?(?![a-z])", r"(?<![a-z])boys?(?![a-z])", r"(?<![a-z])womans?(?![a-z])",
        r"(?<![a-z])mans?(?![a-z])", r"(?<![a-z])ladys?(?![a-z])", r"(?<![a-z])childs?(?![a-z])", r"children", r"(?<![a-z])babys?(?![a-z])",
        r"toddler", r"(?<![a-z])kids?(?![a-z])", r"(?<![a-z])teens?(?![a-z])", r"teenager", r"(?<![a-z])adults?(?![a-z])",
        r"(?<![a-z])seniors?(?![a-z])", r"(?<![a-z])elders?(?![a-z])", r"grandmother", r"grandfather", r"(?<![a-z])mothers?(?![a-z])",
        r"(?<![a-z])fathers?(?![a-z])", r"(?<![a-z])parents?(?![a-z])", r"daughter", r"(?<![a-z])sons?(?![a-z])", r"(?<![a-z])sisters?(?![a-z])",
        r"brother", r"(?<![a-z])friends?(?![a-z])", r"(?<![a-z])couples?(?![a-z])", r"(?<![a-z])familys?(?![a-z])", r"(?<![a-z])groups?(?![a-z])",
        r"(?<![a-z])crowds?(?![a-z])", r"(?<![a-z])selfies?(?![a-z])", r"lifestyle", r"(?<![a-z])picnics?(?![a-z])", r"reading",
        r"(?<![a-z])models?(?![a-z])", r"(?<![a-z])figures?(?![a-z])", r"fashion", r"(?<![a-z])beautys?(?![a-z])", r"(?<![a-z])makeups?(?![a-z])",
        r"hairstyle", r"clothing", r"(?<![a-z])dress(?![a-z])", r"(?<![a-z])suits?(?![a-z])", r"uniform",
        r"traditional_costume", r"(?<![a-z])kimonos?(?![a-z])", r"(?<![a-z])hanfus?(?![a-z])", r"cosplay", r"(?<![a-z])dancers?(?![a-z])",
        r"(?<![a-z])singers?(?![a-z])", r"musician", r"(?<![a-z])brides?(?![a-z])", r"(?<![a-z])grooms?(?![a-z])", r"(?<![a-z])monks?(?![a-z])",
        r"samurai", r"(?<![a-z])geishas?(?![a-z])", r"warrior", r"(?<![a-z])nomads?(?![a-z])", r"shepherd",
        r"photographer", r"(?<![a-z])hikers?(?![a-z])", r"(?<![a-z])workers?(?![a-z])", r"(?<![a-z])farmers?(?![a-z])", r"fisherman",
        r"(?<![a-z])chefs?(?![a-z])", r"(?<![a-z])doctors?(?![a-z])", r"(?<![a-z])nurses?(?![a-z])", r"teacher", r"student",
        r"athlete", r"^people$", r"^person$",
    ],
    "Objects": [
        r"(?<![a-z])items?(?![a-z])", r"(?<![a-z])crafts?(?![a-z])", r"handicraft", r"knitting", r"(?<![a-z])yarns?(?![a-z])",
        r"(?<![a-z])wools?(?![a-z])", r"(?<![a-z])sewings?(?![a-z])", r"embroidery", r"patchwork", r"pottery",
        r"woodworking", r"vintage", r"(?<![a-z])retros?(?![a-z])", r"nostalgia", r"americana",
        r"antique", r"typewriter", r"gramophone", r"(?<![a-z])clocks?(?![a-z])", r"(?<![a-z])books?(?![a-z])",
        r"(?<![a-z])toys?(?![a-z])", r"(?<![a-z])legos?(?![a-z])", r"instrument", r"still_life", r"tableware",
        r"ceramic", r"porcelain", r"(?<![a-z])glass(?![a-z])", r"(?<![a-z])metals?(?![a-z])", r"(?<![a-z])papers?(?![a-z])",
        r"(?<![a-z])fabrics?(?![a-z])", r"leather", r"(?<![a-z])baskets?(?![a-z])", r"(?<![a-z])boxs?(?![a-z])", r"(?<![a-z])bottles?(?![a-z])",
        r"(?<![a-z])vases?(?![a-z])", r"(?<![a-z])bowls?(?![a-z])", r"(?<![a-z])plates?(?![a-z])", r"(?<![a-z])cups?(?![a-z])", r"(?<![a-z])mugs?(?![a-z])",
        r"(?<![a-z])teapots?(?![a-z])", r"(?<![a-z])kettles?(?![a-z])", r"(?<![a-z])candles?(?![a-z])", r"lantern", r"(?<![a-z])lamps?(?![a-z])",
        r"chandelier", r"furniture", r"(?<![a-z])chairs?(?![a-z])", r"(?<![a-z])tables?(?![a-z])", r"(?<![a-z])desks?(?![a-z])",
        r"(?<![a-z])sofas?(?![a-z])", r"(?<![a-z])beds?(?![a-z])", r"cabinet", r"(?<![a-z])shelfs?(?![a-z])", r"(?<![a-z])mirrors?(?![a-z])",
        r"picture_frame", r"figurine", r"(?<![a-z])dolls?(?![a-z])", r"teddy_bear", r"(?<![a-z])puzzles?(?![a-z])",
        r"board_game", r"card_game", r"(?<![a-z])dices?(?![a-z])", r"(?<![a-z])chess(?![a-z])", r"checkers",
        r"backgammon", r"stationery", r"notebook", r"(?<![a-z])pencils?(?![a-z])", r"(?<![a-z])erasers?(?![a-z])",
        r"(?<![a-z])rulers?(?![a-z])", r"scissors", r"(?<![a-z])glues?(?![a-z])", r"(?<![a-z])tapes?(?![a-z])", r"envelope",
        r"(?<![a-z])letters?(?![a-z])", r"postcard", r"(?<![a-z])stamps?(?![a-z])", r"(?<![a-z])coins?(?![a-z])", r"banknote",
        r"jewelry", r"necklace", r"bracelet", r"(?<![a-z])rings?(?![a-z])", r"earrings",
        r"(?<![a-z])watchs?(?![a-z])", r"glasses", r"sunglasses", r"(?<![a-z])hats?(?![a-z])", r"(?<![a-z])caps?(?![a-z])",
        r"(?<![a-z])scarfs?(?![a-z])", r"(?<![a-z])gloves(?![a-z])", r"(?<![a-z])bags?(?![a-z])", r"backpack", r"(?<![a-z])purses?(?![a-z])",
        r"(?<![a-z])wallets?(?![a-z])", r"umbrella", r"(?<![a-z])locks?(?![a-z])", r"(?<![a-z])tools?(?![a-z])", r"(?<![a-z])hammers?(?![a-z])",
        r"screwdriver", r"(?<![a-z])wrenchs?(?![a-z])", r"(?<![a-z])drills?(?![a-z])", r"(?<![a-z])cameras?(?![a-z])", r"(?<![a-z])lens(?![a-z])",
        r"telescope", r"microscope", r"binoculars", r"compass", r"(?<![a-z])globes?(?![a-z])",
        r"(?<![a-z])maps?(?![a-z])", r"(?<![a-z])atlas(?![a-z])", r"suitcase", r"(?<![a-z])barrels?(?![a-z])", r"(?<![a-z])carpets?(?![a-z])",
        r"(?<![a-z])rugs?(?![a-z])", r"curtain", r"(?<![a-z])pillows?(?![a-z])", r"(?<![a-z])quilts?(?![a-z])", r"perfume",
        r"(?<![a-z])soaps?(?![a-z])", r"(?<![a-z])brooms?(?![a-z])", r"(?<![a-z])guitars?(?![a-z])", r"(?<![a-z])pianos?(?![a-z])", r"(?<![a-z])violins?(?![a-z])",
        r"(?<![a-z])flutes?(?![a-z])", r"(?<![a-z])drums?(?![a-z])", r"saxophone", r"trumpet", r"(?<![a-z])harps?(?![a-z])",
        r"accordion", r"ukulele", r"(?<![a-z])vinyls?(?![a-z])", r"record_player", r"(?<![a-z])radios?(?![a-z])",
        r"telephone", r"smartphone", r"(?<![a-z])laptops?(?![a-z])", r"computer", r"keyboard",
        r"^objects?$",
    ],
    "Food": [
        r"(?<![a-z])foods?(?![a-z])", r"(?<![a-z])meals?(?![a-z])", r"(?<![a-z])dishs?(?![a-z])", r"gourmet", r"cuisine",
        r"dessert", r"(?<![a-z])sweets?(?![a-z])", r"(?<![a-z])cakes?(?![a-z])", r"cupcake", r"cheesecake",
        r"(?<![a-z])pastrys?(?![a-z])", r"(?<![a-z])bakerys?(?![a-z])", r"croissant", r"(?<![a-z])breads?(?![a-z])", r"(?<![a-z])bagels?(?![a-z])",
        r"pretzel", r"macaron", r"(?<![a-z])donuts?(?![a-z])", r"(?<![a-z])waffles?(?![a-z])", r"pancake",
        r"(?<![a-z])cookies?(?![a-z])", r"(?<![a-z])pies?(?![a-z])", r"(?<![a-z])tarts?(?![a-z])", r"(?<![a-z])muffins?(?![a-z])", r"ice_cream",
        r"chocolate", r"(?<![a-z])honeys?(?![a-z])", r"(?<![a-z])jams?(?![a-z])", r"(?<![a-z])yogurts?(?![a-z])", r"(?<![a-z])sushis?(?![a-z])",
        r"(?<![a-z])ramens?(?![a-z])", r"(?<![a-z])pizzas?(?![a-z])", r"(?<![a-z])pastas?(?![a-z])", r"(?<![a-z])steaks?(?![a-z])", r"(?<![a-z])dim_sums?(?![a-z])",
        r"(?<![a-z])tacos?(?![a-z])", r"(?<![a-z])burgers?(?![a-z])", r"(?<![a-z])bbqs?(?![a-z])", r"(?<![a-z])hotpots?(?![a-z])", r"dumpling",
        r"(?<![a-z])noodles?(?![a-z])", r"fried_rice", r"fried_chicken", r"sandwich", r"(?<![a-z])hot_dogs?(?![a-z])",
        r"(?<![a-z])kebabs?(?![a-z])", r"spring_roll", r"(?<![a-z])currys?(?![a-z])", r"(?<![a-z])soups?(?![a-z])", r"(?<![a-z])stews?(?![a-z])",
        r"(?<![a-z])salads?(?![a-z])", r"risotto", r"(?<![a-z])paellas?(?![a-z])", r"breakfast", r"(?<![a-z])lunchs?(?![a-z])",
        r"(?<![a-z])dinners?(?![a-z])", r"(?<![a-z])brunchs?(?![a-z])", r"(?<![a-z])snacks?(?![a-z])", r"appetizer", r"(?<![a-z])fruits?(?![a-z])",
        r"(?<![a-z])berrys?(?![a-z])", r"berries", r"strawberry", r"blueberry", r"raspberry",
        r"(?<![a-z])citrus(?![a-z])", r"(?<![a-z])lemons?(?![a-z])", r"(?<![a-z])apples?(?![a-z])", r"(?<![a-z])bananas?(?![a-z])", r"(?<![a-z])oranges?(?![a-z])",
        r"(?<![a-z])grapes?(?![a-z])", r"watermelon", r"(?<![a-z])melons?(?![a-z])", r"(?<![a-z])peachs?(?![a-z])", r"(?<![a-z])cherrys?(?![a-z])",
        r"(?<![a-z])mangos?(?![a-z])", r"pineapple", r"coconut", r"(?<![a-z])kiwis?(?![a-z])", r"avocado",
        r"pomegranate", r"vegetable", r"harvest", r"(?<![a-z])potatos?(?![a-z])", r"sweet_potato",
        r"(?<![a-z])tomatos?(?![a-z])", r"(?<![a-z])carrots?(?![a-z])", r"broccoli", r"spinach", r"lettuce",
        r"cucumber", r"(?<![a-z])onions?(?![a-z])", r"(?<![a-z])garlics?(?![a-z])", r"(?<![a-z])peppers?(?![a-z])", r"(?<![a-z])cheeses?(?![a-z])",
        r"(?<![a-z])butters?(?![a-z])", r"(?<![a-z])eggs?(?![a-z])", r"(?<![a-z])bacons?(?![a-z])", r"sausage", r"(?<![a-z])hams?(?![a-z])",
        r"(?<![a-z])tofus?(?![a-z])", r"(?<![a-z])beans?(?![a-z])", r"seafood", r"(?<![a-z])fishs?(?![a-z])", r"(?<![a-z])shrimps?(?![a-z])",
        r"lobster", r"(?<![a-z])crabs?(?![a-z])", r"(?<![a-z])oysters?(?![a-z])", r"(?<![a-z])mussels?(?![a-z])", r"(?<![a-z])clams?(?![a-z])",
        r"(?<![a-z])squids?(?![a-z])", r"seaweed", r"(?<![a-z])drinks?(?![a-z])", r"beverage", r"(?<![a-z])coffees?(?![a-z])",
        r"(?<![a-z])lattes?(?![a-z])", r"(?<![a-z])teas?(?![a-z])", r"afternoon_tea", r"(?<![a-z])matchas?(?![a-z])", r"cocktail",
        r"(?<![a-z])wines?(?![a-z])", r"(?<![a-z])beers?(?![a-z])", r"whiskey", r"champagne", r"(?<![a-z])sakes?(?![a-z])",
        r"(?<![a-z])juices?(?![a-z])", r"smoothie",
    ],
    "Holidays": [
        r"holiday", r"festival", r"celebration", r"carnival", r"(?<![a-z])parades?(?![a-z])",
        r"fireworks", r"(?<![a-z])partys?(?![a-z])", r"birthday", r"anniversary", r"wedding",
        r"graduation", r"christmas", r"(?<![a-z])xmas(?![a-z])", r"(?<![a-z])santas?(?![a-z])", r"santa_claus",
        r"christmas_tree", r"gingerbread", r"(?<![a-z])advents?(?![a-z])", r"nativity", r"(?<![a-z])hollys?(?![a-z])",
        r"(?<![a-z])sleighs?(?![a-z])", r"halloween", r"jack_o_lantern", r"pumpkin", r"haunted_house",
        r"(?<![a-z])ghosts?(?![a-z])", r"(?<![a-z])witchs?(?![a-z])", r"vampire", r"skeleton", r"(?<![a-z])skulls?(?![a-z])",
        r"(?<![a-z])easters?(?![a-z])", r"easter_egg", r"thanksgiving", r"(?<![a-z])turkeys?(?![a-z])", r"valentine",
        r"spring_festival", r"chinese_new_year", r"lunar_new_year", r"lantern_festival", r"mid_autumn",
        r"mooncake", r"dragon_boat", r"qingming", r"(?<![a-z])qixis?(?![a-z])", r"chongyang",
        r"(?<![a-z])chuxis?(?![a-z])", r"independence_day", r"(?<![a-z])diwalis?(?![a-z])", r"(?<![a-z])holis?(?![a-z])", r"ramadan",
        r"oktoberfest", r"beer_festival", r"(?<![a-z])skiings?(?![a-z])", r"surfing", r"(?<![a-z])soccers?(?![a-z])",
        r"football", r"basketball", r"baseball", r"(?<![a-z])tennis(?![a-z])", r"(?<![a-z])golfs?(?![a-z])",
        r"swimming", r"running", r"cycling", r"(?<![a-z])hikings?(?![a-z])", r"climbing",
        r"fishing", r"(?<![a-z])yogas?(?![a-z])", r"marathon", r"championship", r"world_cup",
        r"new_?year", r"\bsports?\b", r"olympics?",
    ],
    "Art": [
        r"fine_art", r"masterpiece", r"(?<![a-z])museums?(?![a-z])", r"painting", r"oil_painting",
        r"watercolor", r"acrylic", r"gouache", r"(?<![a-z])canvas(?![a-z])", r"(?<![a-z])pastels?(?![a-z])",
        r"charcoal", r"(?<![a-z])sketchs?(?![a-z])", r"drawing", r"line_art", r"pencil_drawing",
        r"illustration", r"storybook", r"picture_book", r"whimsical", r"hand_drawn",
        r"sketchbook", r"(?<![a-z])doodles?(?![a-z])", r"(?<![a-z])animes?(?![a-z])", r"(?<![a-z])mangas?(?![a-z])", r"cartoon",
        r"(?<![a-z])chibis?(?![a-z])", r"(?<![a-z])ghiblis?(?![a-z])", r"cel_shaded", r"oriental", r"asian_art",
        r"chinese_painting", r"(?<![a-z])gongbis?(?![a-z])", r"ink_wash", r"(?<![a-z])sumi_es?(?![a-z])", r"blue_green_landscape",
        r"(?<![a-z])ukiyo_es?(?![a-z])", r"calligraphy", r"typography", r"lettering", r"(?<![a-z])ai_arts?(?![a-z])",
        r"ai_generated", r"digital_art", r"concept_art", r"pixel_art", r"low_poly",
        r"3d_render", r"(?<![a-z])vectors?(?![a-z])", r"flat_design", r"geometric", r"mixed_media",
        r"printmaking", r"lithograph", r"etching", r"screen_print", r"engraving",
        r"woodcut", r"(?<![a-z])posters?(?![a-z])", r"vintage_poster", r"(?<![a-z])mosaics?(?![a-z])", r"tapestry",
        r"stained_glass", r"graffiti", r"(?<![a-z])murals?(?![a-z])", r"street_art", r"installation",
        r"photography", r"abstract", r"surrealism", r"(?<![a-z])cubisms?(?![a-z])", r"(?<![a-z])pop_arts?(?![a-z])",
        r"(?<![a-z])op_arts?(?![a-z])", r"psychedelic", r"baroque", r"renaissance", r"romanticism",
        r"realism", r"expressionism", r"fauvism", r"art_nouveau", r"art_deco",
        r"bauhaus", r"minimalism", r"contemporary_art", r"modern_art", r"classical_art",
        r"folk_art", r"naive_art", r"impressionism", r"van_gogh", r"(?<![a-z])monets?(?![a-z])",
        r"painter", r"illustrator", r"designer", r"art\b", r"arts\b",
        r"fine_?art",
    ],
    "Fantasy": [
        r"fantasy", r"fairy_tale", r"enchanted", r"mythical", r"mythology",
        r"(?<![a-z])dragons?(?![a-z])", r"chinese_dragon", r"unicorn", r"griffin", r"phoenix",
        r"kitsune", r"pegasus", r"mermaid", r"(?<![a-z])fairys?(?![a-z])", r"(?<![a-z])pixies?(?![a-z])",
        r"(?<![a-z])elfs?(?![a-z])", r"(?<![a-z])elves(?![a-z])", r"(?<![a-z])magics?(?![a-z])", r"(?<![a-z])wizards?(?![a-z])", r"sorcerer",
        r"warlock", r"alchemist", r"(?<![a-z])spells?(?![a-z])", r"(?<![a-z])potions?(?![a-z])", r"cauldron",
        r"crystal_cave", r"floating_island", r"(?<![a-z])portals?(?![a-z])", r"magic_circle", r"(?<![a-z])runes?(?![a-z])",
        r"(?<![a-z])sigils?(?![a-z])", r"pentagram", r"crystal_ball", r"(?<![a-z])wands?(?![a-z])", r"(?<![a-z])staffs?(?![a-z])",
        r"spellbook", r"grimoire", r"(?<![a-z])amulets?(?![a-z])", r"talisman", r"(?<![a-z])orbs?(?![a-z])",
        r"chalice", r"world_tree", r"(?<![a-z])spaces?(?![a-z])", r"universe", r"(?<![a-z])cosmos(?![a-z])",
        r"(?<![a-z])galaxys?(?![a-z])", r"galaxies", r"(?<![a-z])nebulas?(?![a-z])", r"(?<![a-z])planets?(?![a-z])", r"(?<![a-z])saturns?(?![a-z])",
        r"(?<![a-z])mars(?![a-z])", r"jupiter", r"(?<![a-z])venus(?![a-z])", r"solar_system", r"asteroid",
        r"(?<![a-z])comets?(?![a-z])", r"(?<![a-z])meteors?(?![a-z])", r"eclipse", r"black_hole", r"supernova",
        r"shooting_star", r"(?<![a-z])rockets?(?![a-z])", r"astronaut", r"spaceship", r"space_station",
        r"(?<![a-z])sci_fis?(?![a-z])", r"wormhole", r"time_travel", r"(?<![a-z])aliens?(?![a-z])", r"(?<![a-z])ufos?(?![a-z])",
        r"(?<![a-z])zodiacs?(?![a-z])", r"astrology", r"horoscope", r"constellation", r"(?<![a-z])tarots?(?![a-z])",
        r"(?<![a-z])dwarfs?(?![a-z])", r"(?<![a-z])gnomes?(?![a-z])", r"(?<![a-z])trolls?(?![a-z])", r"(?<![a-z])goblins?(?![a-z])", r"(?<![a-z])orcs?(?![a-z])",
        r"(?<![a-z])ogres?(?![a-z])", r"(?<![a-z])giants?(?![a-z])", r"(?<![a-z])titans?(?![a-z])", r"(?<![a-z])demons?(?![a-z])", r"(?<![a-z])angels?(?![a-z])",
        r"werewolf", r"(?<![a-z])zombies?(?![a-z])", r"(?<![a-z])spirits?(?![a-z])", r"phantom", r"(?<![a-z])sirens?(?![a-z])",
        r"(?<![a-z])harpys?(?![a-z])", r"centaur", r"minotaur", r"(?<![a-z])hydras?(?![a-z])", r"(?<![a-z])krakens?(?![a-z])",
        r"(?<![a-z])sphinxs?(?![a-z])", r"(?<![a-z])gorgons?(?![a-z])", r"(?<![a-z])medusas?(?![a-z])", r"(?<![a-z])nymphs?(?![a-z])", r"elemental",
        r"(?<![a-z])golems?(?![a-z])", r"automaton", r"(?<![a-z])mechas?(?![a-z])", r"(?<![a-z])cyborgs?(?![a-z])", r"android",
        r"(?<![a-z])yokais?(?![a-z])", r"(?<![a-z])onis?(?![a-z])", r"(?<![a-z])tanukis?(?![a-z])", r"(?<![a-z])qilins?(?![a-z])", r"paladin",
        r"steampunk", r"cyberpunk", r"dystopia", r"(?<![a-z])utopias?(?![a-z])", r"apocalypse",
        r"post_apocalyptic", r"parallel_world", r"alternate_reality", r"(?<![a-z])dreams?(?![a-z])", r"nightmare",
        r"illusion", r"(?<![a-z])swords?(?![a-z])", r"(?<![a-z])shields?(?![a-z])", r"(?<![a-z])armors?(?![a-z])", r"(?<![a-z])helmets?(?![a-z])",
        r"(?<![a-z])crowns?(?![a-z])", r"(?<![a-z])thrones?(?![a-z])", r"treasure", r"(?<![a-z])jewels?(?![a-z])",
    ],
    "Colors": [
        r"^colors?$", r"^colors$", r"^colours?$", r"^palettes?$", r"^colorfuls?$",
        r"^rainbows?$", r"^gradients?$", r"^gradients$", r"^monochromes?$", r"^duotones?$",
        r"^tricolors?$", r"^sepias?$", r"^neons?$", r"^metallics?$", r"^iridescents?$",
        r"^vibrant_palettes?$", r"^muted_colors$", r"^bright_colors$", r"^dark_colors$", r"^warm_colors$",
        r"^cool_colors$", r"^primary_colors$", r"^secondary_colors$", r"^complementary_colors$", r"^black_and_whites?$",
        r"^reds?$", r"^blues?$", r"^greens?$", r"^yellows?$", r"^oranges?$",
        r"^purples?$", r"^pinks?$", r"^browns?$", r"^blacks?$", r"^whites?$",
        r"^grays?$", r"^greys?$", r"^golds?$", r"^silvers?$", r"^bronzes?$",
        r"^coppers?$", r"^turquoises?$", r"^magentas?$", r"^cyans?$", r"^maroons?$",
        r"^navys?$", r"^beiges?$", r"^ivorys?$", r"^olives?$", r"^teals?$",
        r"^indigos?$", r"^violets?$", r"^crimsons?$", r"^scarlets?$", r"^jades?$",
        r"^ambers?$", r"^rose_golds?$",
    ],
    "Composition": [
        r"^compositions?$", r"^flat_lays?$", r"^flatlays?$", r"^knollings?$", r"^collages?$",
        r"^collages$", r"^assortments?$", r"^mandalas?$", r"^kaleidoscopes?$", r"^kaleidoscopes$",
        r"^layouts?$", r"^arrangements?$", r"^patterns?$", r"^textures?$", r"^backgrounds?$",
        r"^wallpapers?$", r"^borders?$", r"^frames?$", r"^grids?$", r"^grid_layouts?$",
        r"^symmetrys?$", r"^asymmetrys?$", r"^minimals?$", r"^minimalists?$", r"^negative_spaces?$",
        r"^leading_lines$", r"^rule_of_thirds$", r"^depth_of_fields?$", r"^bokehs?$", r"^macros?$",
        r"^close_ups?$", r"^wide_angles?$", r"^panoramas?$", r"^tilt_shifts?$", r"^long_exposures?$",
        r"^motion_blurs?$", r"^double_exposures?$", r"^top_downs?$", r"^overheads?$", r"^triptychs?$",
        r"^diptychs?$", r"^frameds?$", r"^polaroids?$", r"^film_strips?$", r"^reflections?$",
        r"^silhouettes?$", r"^high_keys?$", r"^low_keys?$", r"^hdrs?$", r"^fisheyes?$",
        r"^aerials?$", r"^drone_views?$", r"^birds_eyes?$",
    ],
    "Others": [
        r"(?<![a-z])others?(?![a-z])", r"(?<![a-z])others(?![a-z])", r"(?<![a-z])miscs?(?![a-z])",
    ],
}

# 中文别名快速映射字典
ZH_ALIAS_MAP: dict[str, str] = {
    "风光": "Landscapes", "风景": "Landscapes", "雪山": "Landscapes", "山峦": "Landscapes", "湖泊": "Landscapes",
    "森林": "Landscapes", "海洋": "Landscapes", "海滩": "Landscapes", "日落": "Landscapes", "晚霞": "Landscapes",
    "自然": "Nature", "植物": "Nature", "多肉": "Nature", "绿植": "Nature", "蘑菇": "Nature",
    "真菌": "Nature", "四季": "Nature", "花卉": "Flowers", "花朵": "Flowers", "花园": "Flowers",
    "花海": "Flowers", "插花": "Flowers", "玫瑰": "Flowers", "牡丹": "Flowers", "郁金香": "Flowers",
    "动物": "Animals", "野生动物": "Animals", "野兽": "Animals", "鸟类": "Animals", "飞禽": "Animals",
    "海洋水族": "Animals", "水族": "Animals", "宠物": "Pets", "萌宠": "Pets", "猫咪": "Pets",
    "猫": "Pets", "狗狗": "Pets", "狗": "Pets", "兔子": "Pets", "仓鼠": "Pets",
    "荷兰猪": "Pets", "城市": "Cities", "都市": "Cities", "天际线": "Cities", "街景": "Cities",
    "夜景": "Cities", "水乡": "Cities", "小镇": "Cities", "古镇": "Cities", "运河": "Cities",
    "建筑": "Structures", "地标": "Structures", "古堡": "Structures", "城堡": "Structures", "宫殿": "Structures",
    "大厦": "Structures", "桥梁": "Structures", "大桥": "Structures", "灯塔": "Structures", "教堂": "Structures",
    "寺庙": "Structures", "交通": "Vehicles", "机械": "Vehicles", "汽车": "Vehicles", "跑车": "Vehicles",
    "火车": "Vehicles", "列车": "Vehicles", "船舶": "Vehicles", "帆船": "Vehicles", "飞机": "Vehicles",
    "人物": "People", "人像": "People", "肖像": "People", "写真": "People", "女孩": "People",
    "女性": "People", "情侣": "People", "亲子": "People", "童话角色": "People", "物品": "Objects",
    "器物": "Objects", "静物": "Objects", "复古": "Objects", "手作": "Objects", "工艺品": "Objects",
    "玩具": "Objects", "乐器": "Objects", "道具": "Objects", "美食": "Food", "料理": "Food",
    "甜品": "Food", "甜点": "Food", "烘焙": "Food", "蛋糕": "Food", "水果": "Food",
    "咖啡": "Food", "茶饮": "Food", "艺术": "Art", "插画": "Art", "手绘": "Art",
    "名画": "Art", "油画": "Art", "绘本": "Art", "动漫": "Art", "二次元": "Art",
    "国风": "Art", "水墨": "Art", "AI生成": "Art", "AI绘画": "Art", "奇幻": "Fantasy",
    "科幻": "Fantasy", "神兽": "Fantasy", "巨龙": "Fantasy", "魔法": "Fantasy", "太空": "Fantasy",
    "星云": "Fantasy", "星座": "Fantasy", "占星": "Fantasy", "庆典": "Holidays", "节日": "Holidays",
    "节庆": "Holidays", "活动": "Holidays", "运动会": "Holidays", "体育": "Holidays", "赛事": "Holidays",
    "嘉年华": "Holidays", "圣诞": "Holidays", "万圣": "Holidays", "春节": "Holidays", "色彩": "Colors",
    "缤纷": "Colors", "彩虹": "Colors", "色调": "Colors", "撞色": "Colors", "渐变": "Colors",
    "组合": "Composition", "平铺": "Composition", "排布": "Composition", "拼贴": "Composition", "曼陀罗": "Composition",
    "万花筒": "Composition", "其他": "Others", "杂项": "Others",
}
_ZH_ALIAS_MAP = ZH_ALIAS_MAP

# 历史前缀兼容 (cat_*)
LEGACY_CAT_MAP: dict[str, str] = {
    "cat_nature": "Nature",
    "cat_animals": "Animals",
    "cat_pets": "Pets",
    "cat_colors": "Colors",
    "cat_flowers": "Flowers",
    "cat_food": "Food",
    "cat_art": "Art",
    "cat_fantasy": "Fantasy",
    "cat_holidays": "Holidays",
    "cat_landscapes": "Landscapes",
    "cat_vehicles": "Vehicles",
    "cat_travel": "Cities",
    "cat_cozy": "Objects",
    "cat_others": "Others",
    "Travel": "Cities",
    "Cozy": "Objects",
}
_LEGACY_CAT_MAP = LEGACY_CAT_MAP

# ---------------------------------------------------------------------------
# 2b. 全词精确匹配表 (优先于正则子串匹配)
# ---------------------------------------------------------------------------

def _extract_word(pattern: str) -> str | None:
    """从正则中反解出可整串精确匹配的裸词；无法反解则返回 None。"""
    s = pattern
    if s.startswith(r"(?<![a-z])") and s.endswith(r"(?![a-z])"):
        s = s[len(r"(?<![a-z])"):-len(r"(?![a-z])")]
        if s.endswith("s?"):
            s = s[:-2]
    elif s.startswith("^") and s.endswith("$"):
        s = s[1:-1]
        if s.endswith("s?"):
            s = s[:-2]
    elif s.endswith(r"\b"):
        s = s[:-2]
    return s if re.fullmatch(r"[a-z_]+", s) else None


def _build_exact_map() -> dict[str, str]:
    """按主标签顺序构建裸词 -> 标签 的精确表（先出现者优先）。"""
    table: dict[str, str] = {}
    for tag, patterns in TAG_PATTERNS.items():
        if tag == "Others":
            continue
        for pattern in patterns:
            word = _extract_word(pattern)
            if word and word not in table:
                table[word] = tag
    return table


EXACT_MAP: dict[str, str] = _build_exact_map()
_EXACT_MAP = EXACT_MAP


def _exact_lookup(key: str) -> str | None:
    """整串精确查表，带单复数回退。"""
    if key in _EXACT_MAP:
        return _EXACT_MAP[key]
    if key.endswith("s") and key[:-1] in _EXACT_MAP:
        return _EXACT_MAP[key[:-1]]
    if key.endswith("es") and key[:-2] in _EXACT_MAP:
        return _EXACT_MAP[key[:-2]]
    if key.endswith("ies") and (key[:-3] + "y") in _EXACT_MAP:
        return _EXACT_MAP[key[:-3] + "y"]
    if (key + "s") in _EXACT_MAP:
        return _EXACT_MAP[key + "s"]
    return None


# 风格 / 属性类主标签：仅在没有任何主体 TAG 命中时才生效（风格让位于主体）
STYLE_TAGS: set[str] = {'Art', 'Fantasy', 'Colors', 'Composition'}
_STYLE_TAGS = STYLE_TAGS

# 预编译正则，并记录该条的语义长度（用于最长命中优先）
def _pattern_weight(pattern: str) -> int:
    word = _extract_word(pattern)
    return len(word) if word else len(pattern)


COMPILED_PATTERNS: dict[str, list[tuple[re.Pattern, int]]] = {
    tag: [(re.compile(p, re.IGNORECASE), _pattern_weight(p)) for p in patterns]
    for tag, patterns in TAG_PATTERNS.items()
}
_COMPILED_PATTERNS = COMPILED_PATTERNS

# ---------------------------------------------------------------------------
# 3. 归一化与路径智能推断 API
# ---------------------------------------------------------------------------

def get_main_tags() -> list[dict[str, Any]]:
    """获取 17 个核心主 Tags 清单（含 ID、中文名、描述、图标）。"""
    return MAIN_TAGS


def match_best_pattern(text: str) -> str | None:
    """
    在正则中取「语义最长命中」者。分两轮：
      1) 先只在主体类 TAG 中取最长命中；
      2) 主体类一个都没命中时，才在风格/属性类 TAG (Art/Fantasy/Colors/Composition) 中取。
    即：风格 TAG 优先级最低，只要能匹配到任何主体 TAG，就不会归到风格 TAG。
    """
    best_len = -1
    best_tag: str | None = None
    style_len = -1
    style_tag: str | None = None
    for main_tag, compiled in _COMPILED_PATTERNS.items():
        if main_tag == "Others":
            continue
        for pat, weight in compiled:
            if not pat.search(text):
                continue
            if main_tag in _STYLE_TAGS:
                if weight > style_len:
                    style_len = weight
                    style_tag = main_tag
            elif weight > best_len:
                best_len = weight
                best_tag = main_tag
    return best_tag or style_tag


def normalize_tag(tag: str | None) -> str:
    """
    将任意输入的字符串标签归一化为标准的 17 主 Tag ID 之一。
    匹配顺序: 中文别名 -> 历史 cat_ 前缀 -> 主 Tag 全等 -> 全词精确表 -> 正则最长命中。
    例如:
      'cats' -> 'Pets'
      'mountains' -> 'Landscapes'
      'christmas_tree' -> 'Holidays'   (精确表整串命中, 不再被 tree 抢走)
      'oil_painting' -> 'Art'          (最长命中, 不再被 painting 抢走)
      'anime_girl' -> 'People'         (主体 TAG 优先于风格 TAG)
      '猫咪' -> 'Pets'
      'Unknown' -> 'Others'
    """
    if not tag:
        return "Others"

    cleaned = str(tag).strip()
    if not cleaned:
        return "Others"

    # 1. 检查中文别名映射
    if cleaned in _ZH_ALIAS_MAP:
        return _ZH_ALIAS_MAP[cleaned]

    # 2. 检查是否带历史 cat_ 前缀
    lower_cleaned = cleaned.lower()
    if lower_cleaned in _LEGACY_CAT_MAP:
        return _LEGACY_CAT_MAP[lower_cleaned]

    # 3. 检查直接匹配主 Tag (大小写不敏感)
    for main_tag in MAIN_TAG_IDS:
        if lower_cleaned == main_tag.lower():
            return main_tag

    # 4. 全词精确匹配 (目录名整串命中, 支持空格/连字符归一与单复数回退)
    key = re.sub(r"[\s\-]+", "_", lower_cleaned)
    hit = _exact_lookup(key) or _exact_lookup(key.replace("_", ""))
    if hit:
        return hit

    # 5. 正则子串匹配: 取语义最长命中者
    return match_best_pattern(cleaned) or "Others"


def normalize_tags(tags: list[str] | None) -> list[str]:
    """
    将标签列表逐一归一化，去重并保持原始顺序。若全部无法匹配则返回 ['Others']。
    """
    if not tags:
        return ["Others"]

    result: list[str] = []
    seen: set[str] = set()

    for t in tags:
        norm = normalize_tag(t)
        if norm not in seen:
            seen.add(norm)
            result.append(norm)

    return result if result else ["Others"]


def infer_tags_from_path(path: str | Path, root: Path | None = None) -> list[str]:
    """
    从图片文件的路径语义（优先最内层父目录名）智能推断应赋予的主 Tags。
    规则：严格从各级父目录名识别，绝不从文件名推断（避免文件名随机命名导致误判）。
    """
    p = Path(path)

    # 如果有 root 且属于 root 下的子路径，取相对路径解析
    if root is not None:
        try:
            p = p.relative_to(root)
        except Exception as e:
            logger.debug("路径不属于 root，按原路径处理: %s (%s)", p, e)

    # 目录层级（从最靠近文件的父目录向上遍历）
    parent_dirs = list(p.parts[:-1]) if len(p.parts) > 1 else []

    # 1. 优先从最靠近文件的父目录开始识别
    for d in reversed(parent_dirs):
        norm = normalize_tag(d)
        if norm != "Others":
            return [norm]

    # 2. 回退为祖先目录名做正则最长命中（不检查文件名，避免文件名随机字符串造成误判）
    for d in reversed(parent_dirs):
        best = match_best_pattern(d)
        if best:
            return [best]

    return ["Others"]


def suggest_tags_for_image(filename: str, parent_dirs: list[str] | None = None) -> list[str]:
    """基于文件名和父目录列表推荐标签。若有父目录优先从目录识别，无目录时才从文件名识别。"""
    if parent_dirs:
        for d in reversed(parent_dirs):
            norm = normalize_tag(d)
            if norm != "Others":
                return [norm]
    stem = Path(filename).stem
    norm = normalize_tag(stem)
    return [norm]


# ---------------------------------------------------------------------------
# 4. 兼容性导出 (向下兼容历史调用方)
# ---------------------------------------------------------------------------
ALL_CANONICAL_TAGS: list[str] = MAIN_TAG_IDS
CATALOG_TO_TAGS_MAP: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}
TAG_TO_CATALOGS: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}
normalize_token = normalize_tag
guess_tags_from_path = infer_tags_from_path
get_catalogs_for_tags = normalize_tags
