#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_taxonomy.py — Jigsaw Puzzle 分类标签体系代码生成器 (Taxonomy CodeGen)
依据规范: docs/jigsaw-taxonomy-ssot-codegen-specification-20260904.md

单一事实源 (SSOT): data/taxonomy.json
自动生成三端产物:
  1. Flutter/Dart: lib/data/constants/puzzle_tags.dart
  2. Studio Python: studio/taxonomy.py
  3. Web JS:        studio/static/js/taxonomy.js

支持参数:
  --check   : 校验 SSOT 健全性并检查生成文件是否最新 (CI/预检使用，无修改)
  --dry-run : 仅执行校验与内存生成，打印报告而不写入磁盘
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

# 项目根目录定位
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SSOT_FILE = PROJECT_ROOT / "data" / "taxonomy.json"

TARGET_DART = PROJECT_ROOT / "lib" / "data" / "constants" / "puzzle_tags.dart"
TARGET_PYTHON = PROJECT_ROOT / "studio" / "taxonomy.py"
TARGET_JS = PROJECT_ROOT / "studio" / "static" / "js" / "taxonomy.js"


def load_and_validate_ssot(path: Path) -> dict[str, Any]:
    """加载并严格校验 SSOT JSON 数据文件的健全性。"""
    if not path.exists():
        raise FileNotFoundError(f"SSOT 文件不存在: {path}")

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. 主标签校验
    main_tags = data.get("main_tags")
    if not isinstance(main_tags, list) or len(main_tags) != 17:
        raise ValueError(f"main_tags 必须为正好包含 17 个项的列表 (16主业务+1其他)，当前实际为: {len(main_tags) if isinstance(main_tags, list) else type(main_tags)}")

    seen_ids = set()
    seen_orders = set()
    required_fields = ["id", "name", "zh", "icon", "category_type", "description", "grid_row", "order"]

    for idx, tag in enumerate(main_tags):
        for field in required_fields:
            if field not in tag or tag[field] is None:
                raise ValueError(f"主标签 [{idx}] 缺少必填字段: {field}")

        tag_id = tag["id"]
        if tag_id in seen_ids:
            raise ValueError(f"主标签 ID 重复: {tag_id}")
        seen_ids.add(tag_id)

        order = tag["order"]
        if order in seen_orders:
            raise ValueError(f"主标签 order 重复: {order}")
        seen_orders.add(order)

        if not (1 <= tag["grid_row"] <= 6):
            raise ValueError(f"主标签 [{tag_id}] 的 grid_row 必须在 1~6 之间，当前为: {tag['grid_row']}")

    # 2. 正则模式库校验
    patterns = data.get("tag_patterns")
    if not isinstance(patterns, dict):
        raise ValueError("tag_patterns 必须为字典结构")

    for tag_id in seen_ids:
        if tag_id not in patterns:
            raise ValueError(f"tag_patterns 缺少主标签 [{tag_id}] 的模式定义")
        tag_pat_list = patterns[tag_id]
        if not isinstance(tag_pat_list, list) or len(tag_pat_list) == 0:
            raise ValueError(f"主标签 [{tag_id}] 的 patterns 列表不能为空")
        for p in tag_pat_list:
            try:
                re.compile(p, re.IGNORECASE)
            except re.error as err:
                raise ValueError(f"主标签 [{tag_id}] 存在非法正则表达式 '{p}': {err}")

    # 3. 中文别名映射校验
    zh_map = data.get("zh_alias_map")
    if not isinstance(zh_map, dict):
        raise ValueError("zh_alias_map 必须为字典结构")
    for alias, target_id in zh_map.items():
        if target_id not in seen_ids:
            raise ValueError(f"zh_alias_map 别名 '{alias}' 指向未知标签 ID: {target_id}")

    # 4. 历史 cat_ 映射校验
    legacy_map = data.get("legacy_map")
    if not isinstance(legacy_map, dict):
        raise ValueError("legacy_map 必须为字典结构")
    for legacy_key, target_id in legacy_map.items():
        if target_id not in seen_ids:
            raise ValueError(f"legacy_map 键 '{legacy_key}' 指向未知标签 ID: {target_id}")

    return data


def generate_dart_code(data: dict[str, Any]) -> str:
    """生成 Flutter/Dart 常量代码。"""
    version = data.get("version", "3.0.0")
    updated_at = data.get("updated_at", "2026-09-04")
    main_tags = data["main_tags"]
    zh_alias_map = data.get("zh_alias_map", {})

    lines = [
        "// Generated by scripts/build_taxonomy.py. DO NOT EDIT DIRECTLY.",
        f"// Source: data/taxonomy.json (v{version}, {updated_at})",
        "",
        "import 'package:flutter/foundation.dart';",
        "",
        "@immutable",
        "class PuzzleTagItem {",
        "  final String id;",
        "  final String name;",
        "  final String zh;",
        "  final String icon;",
        "  final String categoryType;",
        "  final String description;",
        "  final int gridRow;",
        "  final int order;",
        "",
        "  const PuzzleTagItem({",
        "    required this.id,",
        "    required this.name,",
        "    required this.zh,",
        "    required this.icon,",
        "    required this.categoryType,",
        "    required this.description,",
        "    required this.gridRow,",
        "    required this.order,",
        "  });",
        "}",
        "",
        f"// {len(main_tags)} 个独立静态常量（供代码中防手误引用）",
    ]

    for tag in main_tags:
        lines.append(f"const String kTag{tag['id']} = '{tag['id']}';")

    lines.extend([
        "",
        f"// {len(main_tags)} 主 Tags 列表",
        "const List<PuzzleTagItem> kMainTags = [",
    ])

    for tag in main_tags:
        lines.append("  PuzzleTagItem(")
        lines.append(f"    id: '{tag['id']}',")
        lines.append(f"    name: '{tag['name']}',")
        lines.append(f"    zh: '{tag['zh']}',")
        lines.append(f"    icon: '{tag['icon']}',")
        lines.append(f"    categoryType: '{tag['category_type']}',")
        # 转义单引号
        desc_escaped = tag["description"].replace("'", "\\'")
        lines.append(f"    description: '{desc_escaped}',")
        lines.append(f"    gridRow: {tag['grid_row']},")
        lines.append(f"    order: {tag['order']},")
        lines.append("  ),")

    lines.extend([
        "];",
        "",
        f"// 前台 UI 专用 {len(main_tags) + 1} 项黄金矩阵列表（{len(main_tags)} 主 Tag + 1 All，完美对齐 3 列 × 6 行网格）",
        "const List<Map<String, String>> kHomeTags = [",
        "  {'id': 'all', 'label': '全部', 'icon': '🧩'},",
    ])

    for tag in main_tags:
        lines.append(f"  {{'id': '{tag['id']}', 'label': '{tag['zh']}', 'icon': '{tag['icon']}'}},")

    lines.extend([
        "];",
        "",
        "// 中文转 ID 速查表",
        "const Map<String, String> kTagZhToId = {",
    ])

    for zh, tid in zh_alias_map.items():
        lines.append(f"  '{zh}': '{tid}',")

    lines.extend([
        "};",
        "",
        "// ID 转中文速查表",
        "const Map<String, String> kTagIdToZh = {",
    ])

    for tag in main_tags:
        lines.append(f"  '{tag['id']}': '{tag['zh']}',")

    lines.extend([
        "};",
        "",
    ])

    return "\n".join(lines)


def generate_python_code(data: dict[str, Any]) -> str:
    """生成 Studio Python 模块代码。"""
    version = data.get("version", "3.0.0")
    updated_at = data.get("updated_at", "2026-09-04")
    main_tags = data["main_tags"]
    tag_patterns = data["tag_patterns"]
    zh_alias_map = data.get("zh_alias_map", {})
    legacy_map = data.get("legacy_map", {})

    lines = [
        "#!/usr/bin/env python3",
        "# -*- coding: utf-8 -*-",
        '"""',
        "studio.taxonomy — 拼图游戏统一分类标签规范 (Single Source of Truth)",
        f"Generated by scripts/build_taxonomy.py. DO NOT EDIT DIRECTLY.",
        f"Source: data/taxonomy.json (v{version}, {updated_at})",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import re",
        "from pathlib import Path",
        "from typing import Any",
        "",
        "# ---------------------------------------------------------------------------",
        f"# 1. 核心主 Tags ({len(main_tags)} 个核心分类)",
        "# ---------------------------------------------------------------------------",
        "",
        "MAIN_TAGS: list[dict[str, Any]] = [",
    ]

    for tag in main_tags:
        desc_escaped = tag["description"].replace('"', '\\"')
        lines.append(
            f'    {{"id": "{tag["id"]}", "name": "{tag["name"]}", "zh": "{tag["zh"]}", "icon": "{tag["icon"]}", "desc": "{desc_escaped}", "grid_row": {tag["grid_row"]}, "order": {tag["order"]}}},'
        )

    lines.extend([
        "]",
        "",
        'MAIN_TAG_IDS: list[str] = [t["id"] for t in MAIN_TAGS]',
        'TAG_ZH: dict[str, str] = {t["id"]: t["zh"] for t in MAIN_TAGS}',
        "",
        "# 兼容性别名映射 (代码向下兼容)",
        "CATALOG_DEFS = MAIN_TAGS",
        "SPECIFIC_TAG_DEFS = MAIN_TAGS",
        "",
        "# ---------------------------------------------------------------------------",
        "# 2. 细分标签与路径智能识别正则词表 (tag_patterns)",
        "# ---------------------------------------------------------------------------",
        "",
        "TAG_PATTERNS: dict[str, list[str]] = {",
    ])

    for tag_id, pats in tag_patterns.items():
        lines.append(f'    "{tag_id}": [')
        # 格式化正则字符串列表，每行 5~8 个或适当换行
        chunk = []
        for pat in pats:
            # Python raw string representation
            escaped_pat = pat.replace('"', '\\"')
            chunk.append(f'r"{escaped_pat}"')
            if len(chunk) >= 5:
                lines.append(f"        {', '.join(chunk)},")
                chunk = []
        if chunk:
            lines.append(f"        {', '.join(chunk)},")
        lines.append("    ],")

    lines.extend([
        "}",
        "",
        "# 中文别名快速映射字典",
        "ZH_ALIAS_MAP: dict[str, str] = {",
    ])

    # 每行放若干个中文映射
    zh_items = list(zh_alias_map.items())
    for i in range(0, len(zh_items), 5):
        chunk = [f'"{k}": "{v}"' for k, v in zh_items[i:i+5]]
        lines.append(f"    {', '.join(chunk)},")

    lines.extend([
        "}",
        "_ZH_ALIAS_MAP = ZH_ALIAS_MAP",
        "",
        "# 历史前缀兼容 (cat_*)",
        "LEGACY_CAT_MAP: dict[str, str] = {",
    ])

    for k, v in legacy_map.items():
        lines.append(f'    "{k}": "{v}",')

    lines.extend([
        "}",
        "_LEGACY_CAT_MAP = LEGACY_CAT_MAP",
        "",
        "# 预编译正则，提升百万次扫描推断性能",
        "COMPILED_PATTERNS: dict[str, list[re.Pattern]] = {",
        "    tag: [re.compile(p, re.IGNORECASE) for p in patterns]",
        "    for tag, patterns in TAG_PATTERNS.items()",
        "}",
        "_COMPILED_PATTERNS = COMPILED_PATTERNS",
        "",
        "# ---------------------------------------------------------------------------",
        "# 3. 归一化与路径智能推断 API",
        "# ---------------------------------------------------------------------------",
        "",
        "def get_main_tags() -> list[dict[str, Any]]:",
        '    """获取 14 个核心主 Tags 清单（含 ID、中文名、描述、图标）。"""',
        "    return MAIN_TAGS",
        "",
        "",
        "def normalize_tag(tag: str | None) -> str:",
        '    """',
        "    将任意输入的字符串标签归一化为标准的 14 主 Tag ID 之一。",
        "    例如:",
        "      'cats' -> 'Pets'",
        "      'cat_animals' -> 'Animals'",
        "      'mountains' -> 'Landscapes'",
        "      'coffee' -> 'Food'",
        "      '猫咪' -> 'Pets'",
        "      'Unknown' -> 'Others'",
        '    """',
        "    if not tag:",
        '        return "Others"',
        "",
        "    cleaned = str(tag).strip()",
        "    if not cleaned:",
        '        return "Others"',
        "",
        "    # 1. 检查中文别名映射",
        "    if cleaned in _ZH_ALIAS_MAP:",
        "        return _ZH_ALIAS_MAP[cleaned]",
        "",
        "    # 2. 检查是否带历史 cat_ 前缀",
        "    lower_cleaned = cleaned.lower()",
        "    if lower_cleaned in _LEGACY_CAT_MAP:",
        "        return _LEGACY_CAT_MAP[lower_cleaned]",
        "",
        "    # 3. 检查直接匹配主 Tag (大小写不敏感)",
        "    for main_tag in MAIN_TAG_IDS:",
        "        if lower_cleaned == main_tag.lower():",
        "            return main_tag",
        "",
        "    # 4. 检查是否能通过 patterns 识别",
        "    for main_tag, patterns in _COMPILED_PATTERNS.items():",
        "        for pat in patterns:",
        "            if pat.search(cleaned):",
        "                return main_tag",
        "",
        '    return "Others"',
        "",
        "",
        "def normalize_tags(tags: list[str] | None) -> list[str]:",
        '    """',
        '    将标签列表逐一归一化，去重并保持原始顺序。若全部无法匹配则返回 [\'Others\']。',
        '    """',
        "    if not tags:",
        '        return ["Others"]',
        "",
        "    result: list[str] = []",
        "    seen: set[str] = set()",
        "",
        "    for t in tags:",
        "        norm = normalize_tag(t)",
        "        if norm not in seen:",
        "            seen.add(norm)",
        "            result.append(norm)",
        "",
        '    return result if result else ["Others"]',
        "",
        "",
        "def infer_tags_from_path(path: str | Path, root: Path | None = None) -> list[str]:",
        '    """',
        "    从图片文件的路径语义（优先最内层父目录名）智能推断应赋予的主 Tags。",
        "    规则：严格从各级父目录名识别，绝不从文件名推断（避免文件名随机命名导致误判）。",
        '    """',
        "    p = Path(path)",
        "",
        "    # 如果有 root 且属于 root 下的子路径，取相对路径解析",
        "    if root is not None:",
        "        try:",
        "            p = p.relative_to(root)",
        "        except Exception:",
        "            pass",
        "",
        "    # 目录层级（从最靠近文件的父目录向上遍历）",
        "    parent_dirs = list(p.parts[:-1]) if len(p.parts) > 1 else []",
        "",
        "    # 1. 优先从最靠近文件的父目录开始识别",
        "    for d in reversed(parent_dirs):",
        "        norm = normalize_tag(d)",
        '        if norm != "Others":',
        "            return [norm]",
        "",
        "    # 2. 回退检查祖先目录名正则（不检查文件名，避免文件名随机字符串造成误判）",
        "    for d in reversed(parent_dirs):",
        "        for main_tag, patterns in _COMPILED_PATTERNS.items():",
        '            if main_tag == "Others":',
        "                continue",
        "            for pat in patterns:",
        "                if pat.search(d):",
        "                    return [main_tag]",
        "",
        '    return ["Others"]',
        "",
        "",
        "def suggest_tags_for_image(filename: str, parent_dirs: list[str] | None = None) -> list[str]:",
        '    """基于文件名和父目录列表推荐标签。若有父目录优先从目录识别，无目录时才从文件名识别。"""',
        "    if parent_dirs:",
        "        for d in reversed(parent_dirs):",
        "            norm = normalize_tag(d)",
        '            if norm != "Others":',
        "                return [norm]",
        "    stem = Path(filename).stem",
        "    norm = normalize_tag(stem)",
        "    return [norm]",
        "",
        "",
        "# ---------------------------------------------------------------------------",
        "# 4. 兼容性导出 (向下兼容历史调用方)",
        "# ---------------------------------------------------------------------------",
        "ALL_CANONICAL_TAGS: list[str] = MAIN_TAG_IDS",
        'CATALOG_TO_TAGS_MAP: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}',
        'TAG_TO_CATALOGS: dict[str, list[str]] = {t["id"]: [t["id"]] for t in MAIN_TAGS}',
        "normalize_token = normalize_tag",
        "guess_tags_from_path = infer_tags_from_path",
        "get_catalogs_for_tags = normalize_tags",
        "",
    ])

    return "\n".join(lines)


def generate_js_code(data: dict[str, Any]) -> str:
    """生成 Web 前端 JS 常量模块 (UMD)。"""
    version = data.get("version", "3.0.0")
    updated_at = data.get("updated_at", "2026-09-04")
    main_tags = data["main_tags"]
    grid = data.get("grid", {"columns": 3, "rows": 5, "total_slots": 15})
    legacy_map = data.get("legacy_map", {})
    tag_zh = {t["id"]: t["zh"] for t in main_tags}

    payload = {
        "version": version,
        "updated_at": updated_at,
        "grid": grid,
        "main_tags": main_tags,
        "tag_zh": tag_zh,
        "legacy_map": legacy_map,
    }

    json_str = json.dumps(payload, ensure_ascii=False, indent=2)

    lines = [
        "// Generated by scripts/build_taxonomy.py. DO NOT EDIT DIRECTLY.",
        f"// Source: data/taxonomy.json (v{version}, {updated_at})",
        "",
        "(function (global) {",
        f"  const TAXONOMY = {json_str};",
        "",
        '  if (typeof module !== "undefined" && module.exports) {',
        "    module.exports = TAXONOMY;",
        "  } else {",
        "    global.TAXONOMY = TAXONOMY;",
        "  }",
        '})(typeof window !== "undefined" ? window : globalThis);',
        "",
    ]

    return "\n".join(lines)


def atomic_write(target_path: Path, content: str) -> bool:
    """写入文件前先检查内容是否有变化，避免不必要的 mtime 变动；支持原子写入。"""
    target_path.parent.mkdir(parents=True, exist_ok=True)

    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if existing == content:
            return False  # 未发生内容变更

    # 先写入临时文件，再重命名以实现原子替换
    tmp_path = target_path.with_suffix(target_path.suffix + ".tmp")
    tmp_path.write_text(content, encoding="utf-8")
    tmp_path.replace(target_path)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Jigsaw Puzzle Taxonomy CodeGen")
    parser.add_argument("--check", action="store_true", help="校验 SSOT 并检查生成文件是否最新，不写入文件")
    parser.add_argument("--dry-run", action="store_true", help="仅在内存中运行生成，打印报告而不写入文件")
    args = parser.parse_args()

    print(f"[*] 正在读取并校验单一事实源 SSOT: {SSOT_FILE.relative_to(PROJECT_ROOT)} ...")
    try:
        data = load_and_validate_ssot(SSOT_FILE)
    except Exception as e:
        print(f"[ERROR] SSOT 数据校验失败: {e}", file=sys.stderr)
        return 1

    print(f"[OK] SSOT 校验通过: v{data.get('version')} ({len(data['main_tags'])} 主标签, {len(data['tag_patterns'])} 正则组)")

    # 生成各端内容
    dart_code = generate_dart_code(data)
    py_code = generate_python_code(data)
    js_code = generate_js_code(data)

    targets = [
        ("Flutter / Dart", TARGET_DART, dart_code),
        ("Studio Python", TARGET_PYTHON, py_code),
        ("Web JS", TARGET_JS, js_code),
    ]

    if args.check:
        print("[*] 正在执行 --check 检查目标文件是否与 SSOT 完全同步 ...")
        all_synced = True
        for name, path, code in targets:
            if not path.exists():
                print(f"  [MISSING] {name}: {path.relative_to(PROJECT_ROOT)} 不存在")
                all_synced = False
            else:
                existing = path.read_text(encoding="utf-8")
                if existing != code:
                    print(f"  [OUTDATED] {name}: {path.relative_to(PROJECT_ROOT)} 内容与 SSOT 不同步")
                    all_synced = False
                else:
                    print(f"  [UP-TO-DATE] {name}: {path.relative_to(PROJECT_ROOT)}")

        if not all_synced:
            print("[FAIL] 部分生成文件不同步或缺失，请运行 python scripts/build_taxonomy.py 进行同步更新", file=sys.stderr)
            return 1
        print("[SUCCESS] 所有目标文件均与 SSOT 保持最新同步！")
        return 0

    if args.dry_run:
        print("[*] 正在执行 --dry-run 试运行 (不写入磁盘) ...")
        for name, path, code in targets:
            rel = path.relative_to(PROJECT_ROOT)
            lines_cnt = len(code.splitlines())
            bytes_cnt = len(code.encode("utf-8"))
            print(f"  [DRY-RUN] {name} -> {rel} ({lines_cnt} 行, {bytes_cnt} 字节)")
        print("[SUCCESS] Dry run 校验与生成逻辑全部成功！")
        return 0

    print("[*] 正在写入各端生成产物 ...")
    for name, path, code in targets:
        rel = path.relative_to(PROJECT_ROOT)
        changed = atomic_write(path, code)
        status = "已更新写入" if changed else "内容一致(未变动)"
        lines_cnt = len(code.splitlines())
        bytes_cnt = len(code.encode("utf-8"))
        print(f"  [GEN] {name} -> {rel} ({status}, {lines_cnt} 行, {bytes_cnt} 字节)")

    print("[SUCCESS] Taxonomy 代码生成完成！")
    return 0


if __name__ == "__main__":
    sys.exit(main())
